/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const fritekstTilBrevTextArea: string;

export {
	fritekstTilBrevTextArea
};

declare const __default_export__: {
	fritekstTilBrevTextArea: typeof fritekstTilBrevTextArea;
};
export default __default_export__;
