/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const fritekstTilBrevTextArea: string;

export {
	fritekstTilBrevTextArea
};

declare const __default_export__: {
	fritekstTilBrevTextArea: typeof fritekstTilBrevTextArea;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZnJpdGVrc3RLbGFnZUJyZXZUZXh0RmllbGQubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJmcml0ZWtzdEtsYWdlQnJldlRleHRGaWVsZC5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7OztDQUFBOzs7O0NBQUE7OyJ9
