/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const sats: string;
declare const dagsatsSection: string;
declare const firstHeaderCell: string;
declare const noBottomBorder: string;
declare const utbetalingText: string;
declare const sum: string;

export {
	sats,
	dagsatsSection,
	firstHeaderCell,
	noBottomBorder,
	utbetalingText,
	sum
};

declare const __default_export__: {
	sats: typeof sats;
	dagsatsSection: typeof dagsatsSection;
	firstHeaderCell: typeof firstHeaderCell;
	noBottomBorder: typeof noBottomBorder;
	utbetalingText: typeof utbetalingText;
	sum: typeof sum;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZGFnc2F0c09nVXRiZXRhbGluZy5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbImRhZ3NhdHNPZ1V0YmV0YWxpbmcubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBTUE7Y0FJQTtjQUlBO2NBS0E7Y0FJQTs7O0NBdkJBO0NBTUE7Q0FJQTtDQUlBO0NBS0E7Q0FJQTs7OztDQXZCQTtDQU1BO0NBSUE7Q0FJQTtDQUtBO0NBSUE7OyJ9
