/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const sats: string;
declare const dagsatsSection: string;
declare const firstHeaderCell: string;
declare const noBottomBorder: string;
declare const utbetalingText: string;
declare const sum: string;

export { sats, dagsatsSection, firstHeaderCell, noBottomBorder, utbetalingText, sum };

declare const __default_export__: {
  sats: typeof sats;
  dagsatsSection: typeof dagsatsSection;
  firstHeaderCell: typeof firstHeaderCell;
  noBottomBorder: typeof noBottomBorder;
  utbetalingText: typeof utbetalingText;
  sum: typeof sum;
};
export default __default_export__;
