/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const dataBox: string;
declare const utbetalingText: string;
declare const expandButton: string;

export {
	dataBox,
	utbetalingText,
	expandButton
};

declare const __default_export__: {
	dataBox: typeof dataBox;
	utbetalingText: typeof utbetalingText;
	expandButton: typeof expandButton;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZGF0YVNlY3Rpb24ubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJkYXRhU2VjdGlvbi5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FPQTtjQUlBOzs7Q0FYQTtDQU9BO0NBSUE7Ozs7Q0FYQTtDQU9BO0NBSUE7OyJ9
