/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const list: string;

export { list };

declare const __default_export__: {
  list: typeof list;
};
export default __default_export__;
