/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const vurderDatoContainer: string;
declare const info: string;
declare const alertAccordion: string;

export { vurderDatoContainer, info, alertAccordion };

declare const __default_export__: {
  vurderDatoContainer: typeof vurderDatoContainer;
  info: typeof info;
  alertAccordion: typeof alertAccordion;
};
export default __default_export__;
