/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const vurderDatoContainer: string;
declare const info: string;
declare const alertAccordion: string;

export {
	vurderDatoContainer,
	info,
	alertAccordion
};

declare const __default_export__: {
	vurderDatoContainer: typeof vurderDatoContainer;
	info: typeof info;
	alertAccordion: typeof alertAccordion;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVnVyZGVyRGF0by5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbIlZ1cmRlckRhdG8ubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBS0E7Y0FLQTs7O0NBVkE7Q0FLQTtDQUtBOzs7O0NBVkE7Q0FLQTtDQUtBOzsifQ==
