/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const vurderDatoAksjonspunktContainer: string;
declare const knapper: string;
declare const bekreft: string;

export {
	vurderDatoAksjonspunktContainer,
	knapper,
	bekreft
};

declare const __default_export__: {
	vurderDatoAksjonspunktContainer: typeof vurderDatoAksjonspunktContainer;
	knapper: typeof knapper;
	bekreft: typeof bekreft;
};
export default __default_export__;
