/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const vurderDatoAksjonspunktContainer: string;
declare const knapper: string;
declare const bekreft: string;

export {
	vurderDatoAksjonspunktContainer,
	knapper,
	bekreft
};

declare const __default_export__: {
	vurderDatoAksjonspunktContainer: typeof vurderDatoAksjonspunktContainer;
	knapper: typeof knapper;
	bekreft: typeof bekreft;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVnVyZGVyRGF0b0Frc2pvbnNwdW5rdC5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbIlZ1cmRlckRhdG9Ba3Nqb25zcHVua3QubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBU0E7Y0FLQTs7O0NBZEE7Q0FTQTtDQUtBOzs7O0NBZEE7Q0FTQTtDQUtBOzsifQ==
