import type { k9_sak_web_app_tjenester_behandling_opplæringspenger_visning_institusjon_InstitusjonVurderingDto } from '@k9-sak-web/backend/k9sak/generated/types.js';

export type InstitusjonVurderingDto = k9_sak_web_app_tjenester_behandling_opplæringspenger_visning_institusjon_InstitusjonVurderingDto;
