/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const buttonContainer: string;
declare const aksjonspunktHeading: string;
declare const errorMessage: string;

export {
	buttonContainer,
	aksjonspunktHeading,
	errorMessage
};

declare const __default_export__: {
	buttonContainer: typeof buttonContainer;
	aksjonspunktHeading: typeof aksjonspunktHeading;
	errorMessage: typeof errorMessage;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoibWFya2VyQmVoYW5kbGluZ01vZGFsLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsibWFya2VyQmVoYW5kbGluZ01vZGFsLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQUtBO2NBSUE7OztDQVRBO0NBS0E7Q0FJQTs7OztDQVRBO0NBS0E7Q0FJQTs7In0=
