/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const buttonContainer: string;
declare const aksjonspunktHeading: string;
declare const errorMessage: string;

export {
	buttonContainer,
	aksjonspunktHeading,
	errorMessage
};

declare const __default_export__: {
	buttonContainer: typeof buttonContainer;
	aksjonspunktHeading: typeof aksjonspunktHeading;
	errorMessage: typeof errorMessage;
};
export default __default_export__;
