/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const tag: string;

export {
	tag
};

declare const __default_export__: {
	tag: typeof tag;
};
export default __default_export__;
