/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const etikett: string;

export {
	etikett
};

declare const __default_export__: {
	etikett: typeof etikett;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidmlzaXR0a29ydExhYmVscy5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbInZpc2l0dGtvcnRMYWJlbHMubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBOzs7Q0FBQTs7OztDQUFBOzsifQ==
