/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const labels: string;
declare const etikett: string;

export {
	container,
	labels,
	etikett
};

declare const __default_export__: {
	container: typeof container;
	labels: typeof labels;
	etikett: typeof etikett;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidmlzaXR0a29ydERldGFsamVyUG9wdXAubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJ2aXNpdHRrb3J0RGV0YWxqZXJQb3B1cC5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FLQTtjQUlBOzs7Q0FUQTtDQUtBO0NBSUE7Ozs7Q0FUQTtDQUtBO0NBSUE7OyJ9
