/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const labels: string;
declare const etikett: string;

export {
	container,
	labels,
	etikett
};

declare const __default_export__: {
	container: typeof container;
	labels: typeof labels;
	etikett: typeof etikett;
};
export default __default_export__;
