/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const etikett: string;

export {
	etikett
};

declare const __default_export__: {
	etikett: typeof etikett;
};
export default __default_export__;
