/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const begrunnelseWrapper: string;

export {
	begrunnelseWrapper
};

declare const __default_export__: {
	begrunnelseWrapper: typeof begrunnelseWrapper;
};
export default __default_export__;
