/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const begrunnelseWrapper: string;

export {
	begrunnelseWrapper
};

declare const __default_export__: {
	begrunnelseWrapper: typeof begrunnelseWrapper;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYWt0aXZpdGV0UmFkLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsiYWt0aXZpdGV0UmFkLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTs7O0NBQUE7Ozs7Q0FBQTs7In0=
