/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const overstyringSkjemaAktiviteter: string;
declare const overstyringSkjemaAktivitet: string;
declare const aktiviteterTable: string;

export {
	overstyringSkjemaAktiviteter,
	overstyringSkjemaAktivitet,
	aktiviteterTable
};

declare const __default_export__: {
	overstyringSkjemaAktiviteter: typeof overstyringSkjemaAktiviteter;
	overstyringSkjemaAktivitet: typeof overstyringSkjemaAktivitet;
	aktiviteterTable: typeof aktiviteterTable;
};
export default __default_export__;
