/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const overstyringSkjemaWrapper: string;
declare const overstyringDatoOgUttaksgrad: string;
declare const overstyringDatoVelger: string;
declare const overstyringKnapperad: string;
declare const overstyringBegrunnelse: string;
declare const overstyringAktivitetListe: string;

export {
	overstyringSkjemaWrapper,
	overstyringDatoOgUttaksgrad,
	overstyringDatoVelger,
	overstyringKnapperad,
	overstyringBegrunnelse,
	overstyringAktivitetListe
};

declare const __default_export__: {
	overstyringSkjemaWrapper: typeof overstyringSkjemaWrapper;
	overstyringDatoOgUttaksgrad: typeof overstyringDatoOgUttaksgrad;
	overstyringDatoVelger: typeof overstyringDatoVelger;
	overstyringKnapperad: typeof overstyringKnapperad;
	overstyringBegrunnelse: typeof overstyringBegrunnelse;
	overstyringAktivitetListe: typeof overstyringAktivitetListe;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoib3ZlcnN0eXJpbmdVdHRha0Zvcm0ubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJvdmVyc3R5cmluZ1V0dGFrRm9ybS5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FVQTtjQVNBO2NBWUE7Y0FRQTtjQUlBOzs7Q0EzQ0E7Q0FVQTtDQVNBO0NBWUE7Q0FRQTtDQUlBOzs7O0NBM0NBO0NBVUE7Q0FTQTtDQVlBO0NBUUE7Q0FJQTs7In0=
