/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const overstyringSkjemaWrapper: string;
declare const overstyringDatoOgUttaksgrad: string;
declare const overstyringDatoVelger: string;
declare const overstyringKnapperad: string;
declare const overstyringBegrunnelse: string;
declare const overstyringAktivitetListe: string;
declare const overstyringDatoFeil: string;

export {
	overstyringSkjemaWrapper,
	overstyringDatoOgUttaksgrad,
	overstyringDatoVelger,
	overstyringKnapperad,
	overstyringBegrunnelse,
	overstyringAktivitetListe,
	overstyringDatoFeil
};

declare const __default_export__: {
	overstyringSkjemaWrapper: typeof overstyringSkjemaWrapper;
	overstyringDatoOgUttaksgrad: typeof overstyringDatoOgUttaksgrad;
	overstyringDatoVelger: typeof overstyringDatoVelger;
	overstyringKnapperad: typeof overstyringKnapperad;
	overstyringBegrunnelse: typeof overstyringBegrunnelse;
	overstyringAktivitetListe: typeof overstyringAktivitetListe;
	overstyringDatoFeil: typeof overstyringDatoFeil;
};
export default __default_export__;
