enum AvvikIMType {
  SØKNAD_UTEN_MATCHENDE_IM = 'SØKNAD_UTEN_MATCHENDE_IM',
  IM_REFUSJONSKRAV_TRUMFER_SØKNAD = 'IM_REFUSJONSKRAV_TRUMFER_SØKNAD',
  INGEN_AVVIK = 'INGEN_AVVIK',
  UDEFINERT = 'UDEFINERT',
}
export default AvvikIMType