enum Soknadsårsak {
  ARBEIDSGIVER_KONKURS = 'ARBEIDSGIVER_KONKURS',
  NYOPPSTARTET_HOS_ARBEIDSGIVER = 'NYOPPSTARTET_HOS_ARBEIDSGIVER',
  KONFLIKT_MED_ARBEIDSGIVER = 'KONFLIKT_MED_ARBEIDSGIVER',
  UDEFINERT = 'UDEFINERT',
}

export default Soknadsårsak;
