import stringEnum from '@k9-sak-web/types/src/tsUtils';

export const VilkårEnum = stringEnum({
  OMSORGSVILKÅRET: 'OMSORGSVILKÅRET',
  NOK_DAGER: 'NOK_DAGER',
  OPPTJENINGSVILKÅR: 'OPPTJENINGSVILKÅR',
  MEDLEMSKAPSVILKÅR: 'MEDLEMSKAPSVILKÅR',
  ALDERSVILKÅR_SØKER: 'ALDERSVILKÅR_SØKER',
  ALDERSVILKÅR_BARN: 'ALDERSVILKÅR_BARN',
  SMITTEVERN: 'SMITTEVERN',
  LEGEERKLÆRING: 'LEGEERKLÆRING',
  UIDENTIFISERT_RAMMEVEDTAK: 'UIDENTIFISERT_RAMMEVEDTAK'
});

type Vilkår = typeof VilkårEnum[keyof typeof VilkårEnum];

export default Vilkår;

