/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const contentContainer: string;
declare const sideMenuContainer: string;
declare const mainContainerWithSideMenu: string;
declare const warningIcon: string;

export {
	contentContainer,
	sideMenuContainer,
	mainContainerWithSideMenu,
	warningIcon
};

declare const __default_export__: {
	contentContainer: typeof contentContainer;
	sideMenuContainer: typeof sideMenuContainer;
	mainContainerWithSideMenu: typeof mainContainerWithSideMenu;
	warningIcon: typeof warningIcon;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU29rbmFkc2ZyaXN0Vmlsa2FyUHJvc2Vzc0luZGV4Lm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsiU29rbmFkc2ZyaXN0Vmlsa2FyUHJvc2Vzc0luZGV4Lm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQUlBO2NBU0E7Y0FLQTs7O0NBbEJBO0NBSUE7Q0FTQTtDQUtBOzs7O0NBbEJBO0NBSUE7Q0FTQTtDQUtBOzsifQ==
