/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const contentContainer: string;
declare const sideMenuContainer: string;
declare const mainContainerWithSideMenu: string;
declare const warningIcon: string;

export {
	contentContainer,
	sideMenuContainer,
	mainContainerWithSideMenu,
	warningIcon
};

declare const __default_export__: {
	contentContainer: typeof contentContainer;
	sideMenuContainer: typeof sideMenuContainer;
	mainContainerWithSideMenu: typeof mainContainerWithSideMenu;
	warningIcon: typeof warningIcon;
};
export default __default_export__;
