/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const ingenAvrunding: string;

export {
	ingenAvrunding
};

declare const __default_export__: {
	ingenAvrunding: typeof ingenAvrunding;
};
export default __default_export__;
