/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const reportText: string;

export {
	reportText
};

declare const __default_export__: {
	reportText: typeof reportText;
};
export default __default_export__;
