/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const handCursor: string;

export {
	handCursor
};

declare const __default_export__: {
	handCursor: typeof handCursor;
};
export default __default_export__;
