import type { foreldrepenger_tilbakekreving_web_app_tjenester_behandling_dto_BehandlingÅrsakDto } from '@navikt/k9-tilbake-typescript-client/types';

export type BehandlingÅrsakDto = foreldrepenger_tilbakekreving_web_app_tjenester_behandling_dto_BehandlingÅrsakDto;
