/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const visuallyHidden: string;

export { visuallyHidden };

declare const __default_export__: {
  visuallyHidden: typeof visuallyHidden;
};
export default __default_export__;
