/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const sideMenuContainer: string;
declare const mainContainerWithSideMenu: string;

export {
	sideMenuContainer,
	mainContainerWithSideMenu
};

declare const __default_export__: {
	sideMenuContainer: typeof sideMenuContainer;
	mainContainerWithSideMenu: typeof mainContainerWithSideMenu;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidmlsa2FycmVzdWx0YXRNZWRPdmVyc3R5cmluZ1Byb3Nlc3NJbmRleC5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbInZpbGthcnJlc3VsdGF0TWVkT3ZlcnN0eXJpbmdQcm9zZXNzSW5kZXgubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBUUE7OztDQVJBO0NBUUE7Ozs7Q0FSQTtDQVFBOzsifQ==
