/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const sideMenuContainer: string;
declare const mainContainerWithSideMenu: string;

export {
	sideMenuContainer,
	mainContainerWithSideMenu
};

declare const __default_export__: {
	sideMenuContainer: typeof sideMenuContainer;
	mainContainerWithSideMenu: typeof mainContainerWithSideMenu;
};
export default __default_export__;
