version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.READER_TOKEN}}
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 30
    registries:
      - npm-github
    groups:
      patch-and-minor:
        patterns:
          - '*'
        update-types:
          - 'patch'
          - 'minor'
        exclude-patterns:
          - 'react*'
          - '@types/react'
          - '@navikt*'
          - 'eslint-plugin-vitest' # version 0.5.4 requires eslint version 9
      storybook:
        update-types:
          - 'major'
        patterns:
          - 'storybook'
          - '@storybook/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
      designsystem:
        patterns:
          - '@navikt/aksel-icons'
          - '@navikt/ds-*'
      ft-frontend:
        patterns:
          - '@navikt/ft-*'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    groups:
      github:
        patterns:
          - '*'
