/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const fagsakLenke: string;
declare const fagsakLenkeContainer: string;

export {
	fagsakLenke,
	fagsakLenkeContainer
};

declare const __default_export__: {
	fagsakLenke: typeof fagsakLenke;
	fagsakLenkeContainer: typeof fagsakLenkeContainer;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYW5kcmVTYWtlclDDpVPDuGtlclN0cmlwZS5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbImFuZHJlU2FrZXJQw6VTw7hrZXJTdHJpcGUubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBSUE7OztDQUpBO0NBSUE7Ozs7Q0FKQTtDQUlBOzsifQ==
