/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const sakerGrid: string;
declare const historisk: string;

export {
	sakerGrid,
	historisk
};

declare const __default_export__: {
	sakerGrid: typeof sakerGrid;
	historisk: typeof historisk;
};
export default __default_export__;
