/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const antallDagerLivetsSluttfaseIndexContainer: string;
declare const header: string;
declare const sistePleiedagBoks: string;

export {
	antallDagerLivetsSluttfaseIndexContainer,
	header,
	sistePleiedagBoks
};

declare const __default_export__: {
	antallDagerLivetsSluttfaseIndexContainer: typeof antallDagerLivetsSluttfaseIndexContainer;
	header: typeof header;
	sistePleiedagBoks: typeof sistePleiedagBoks;
};
export default __default_export__;
