/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const status: string;
declare const key: string;
declare const keyWithoutCursor: string;
declare const aksjonspunkt: string;
declare const apentAksjonspunkt: string;

export {
	status,
	key,
	keyWithoutCursor,
	aksjonspunkt,
	apentAksjonspunkt
};

declare const __default_export__: {
	status: typeof status;
	key: typeof key;
	keyWithoutCursor: typeof keyWithoutCursor;
	aksjonspunkt: typeof aksjonspunkt;
	apentAksjonspunkt: typeof apentAksjonspunkt;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU29rbmFkc2ZyaXN0Vmlsa2FyRm9ybS5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbIlNva25hZHNmcmlzdFZpbGthckZvcm0ubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBS0E7Y0FNQTtjQUtBO2NBTUE7OztDQXRCQTtDQUtBO0NBTUE7Q0FLQTtDQU1BOzs7O0NBdEJBO0NBS0E7Q0FNQTtDQUtBO0NBTUE7OyJ9
