/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const image: string;
declare const fullBreddeIE: string;
declare const editButton: string;

export { container, image, fullBreddeIE, editButton };

declare const __default_export__: {
  container: typeof container;
  image: typeof image;
  fullBreddeIE: typeof fullBreddeIE;
  editButton: typeof editButton;
};
export default __default_export__;
