/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const image: string;
declare const fullBreddeIE: string;
declare const editButton: string;

export {
	container,
	image,
	fullBreddeIE,
	editButton
};

declare const __default_export__: {
	container: typeof container;
	image: typeof image;
	fullBreddeIE: typeof fullBreddeIE;
	editButton: typeof editButton;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU29rbmFkc2ZyaXN0Vmlsa2FyRG9rdW1lbnQubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJTb2tuYWRzZnJpc3RWaWxrYXJEb2t1bWVudC5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FJQTtjQU1BO2NBSUE7OztDQWRBO0NBSUE7Q0FNQTtDQUlBOzs7O0NBZEE7Q0FJQTtDQU1BO0NBSUE7OyJ9
