/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const status: string;
declare const key: string;
declare const keyWithoutCursor: string;
declare const aksjonspunkt: string;
declare const apentAksjonspunkt: string;

export { status, key, keyWithoutCursor, aksjonspunkt, apentAksjonspunkt };

declare const __default_export__: {
  status: typeof status;
  key: typeof key;
  keyWithoutCursor: typeof keyWithoutCursor;
  aksjonspunkt: typeof aksjonspunkt;
  apentAksjonspunkt: typeof apentAksjonspunkt;
};
export default __default_export__;
