/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const dodEtikett: string;
declare const ieFlex: string;

export {
	dodEtikett,
	ieFlex
};

declare const __default_export__: {
	dodEtikett: typeof dodEtikett;
	ieFlex: typeof ieFlex;
};
export default __default_export__;
