/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const datoRad: string;
declare const boks: string;
declare const datoVelger: string;
declare const periodeHeader: string;

export {
	datoRad,
	boks,
	datoVelger,
	periodeHeader
};

declare const __default_export__: {
	datoRad: typeof datoRad;
	boks: typeof boks;
	datoVelger: typeof datoVelger;
	periodeHeader: typeof periodeHeader;
};
export default __default_export__;
