/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const datoRad: string;
declare const boks: string;
declare const datoVelger: string;
declare const periodeHeader: string;

export {
	datoRad,
	boks,
	datoVelger,
	periodeHeader
};

declare const __default_export__: {
	datoRad: typeof datoRad;
	boks: typeof boks;
	datoVelger: typeof datoVelger;
	periodeHeader: typeof periodeHeader;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicGVyaW9kZXNwbGl0dE1vZGFsLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsicGVyaW9kZXNwbGl0dE1vZGFsLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQU1BO2NBSUE7Y0FJQTs7O0NBZEE7Q0FNQTtDQUlBO0NBSUE7Ozs7Q0FkQTtDQU1BO0NBSUE7Q0FJQTs7In0=
