/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const tilkommetAktivitet: string;
declare const aktivitetContainer: string;
declare const aktivitetTable: string;
declare const separator: string;
declare const aksjonspunktContainer: string;
declare const aksjonspunktContainerLukketAP: string;
declare const bruttoInntektContainer: string;
declare const bruttoInntektCurrency: string;
declare const edited: string;
declare const inntektsmeldingTag: string;
declare const inntektColumn: string;
declare const modalKnapp: string;

export {
	tilkommetAktivitet,
	aktivitetContainer,
	aktivitetTable,
	separator,
	aksjonspunktContainer,
	aksjonspunktContainerLukketAP,
	bruttoInntektContainer,
	bruttoInntektCurrency,
	edited,
	inntektsmeldingTag,
	inntektColumn,
	modalKnapp
};

declare const __default_export__: {
	tilkommetAktivitet: typeof tilkommetAktivitet;
	aktivitetContainer: typeof aktivitetContainer;
	aktivitetTable: typeof aktivitetTable;
	separator: typeof separator;
	aksjonspunktContainer: typeof aksjonspunktContainer;
	aksjonspunktContainerLukketAP: typeof aksjonspunktContainerLukketAP;
	bruttoInntektContainer: typeof bruttoInntektContainer;
	bruttoInntektCurrency: typeof bruttoInntektCurrency;
	edited: typeof edited;
	inntektsmeldingTag: typeof inntektsmeldingTag;
	inntektColumn: typeof inntektColumn;
	modalKnapp: typeof modalKnapp;
};
export default __default_export__;
