/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const statusOk: string;

export { statusOk };

declare const __default_export__: {
  statusOk: typeof statusOk;
};
export default __default_export__;
