/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const tilkommetAktivitet: string;
declare const aktivitetContainer: string;
declare const aktivitetTable: string;
declare const separator: string;
declare const aksjonspunktContainer: string;
declare const aksjonspunktContainerLukketAP: string;
declare const bruttoInntektContainer: string;
declare const bruttoInntektCurrency: string;
declare const edited: string;
declare const inntektsmeldingTag: string;
declare const inntektColumn: string;
declare const modalKnapp: string;

export {
	tilkommetAktivitet,
	aktivitetContainer,
	aktivitetTable,
	separator,
	aksjonspunktContainer,
	aksjonspunktContainerLukketAP,
	bruttoInntektContainer,
	bruttoInntektCurrency,
	edited,
	inntektsmeldingTag,
	inntektColumn,
	modalKnapp
};

declare const __default_export__: {
	tilkommetAktivitet: typeof tilkommetAktivitet;
	aktivitetContainer: typeof aktivitetContainer;
	aktivitetTable: typeof aktivitetTable;
	separator: typeof separator;
	aksjonspunktContainer: typeof aksjonspunktContainer;
	aksjonspunktContainerLukketAP: typeof aksjonspunktContainerLukketAP;
	bruttoInntektContainer: typeof bruttoInntektContainer;
	bruttoInntektCurrency: typeof bruttoInntektCurrency;
	edited: typeof edited;
	inntektsmeldingTag: typeof inntektsmeldingTag;
	inntektColumn: typeof inntektColumn;
	modalKnapp: typeof modalKnapp;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidGlsa29tbWV0QWt0aXZpdGV0Lm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsidGlsa29tbWV0QWt0aXZpdGV0Lm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQUlBO2NBSUE7Y0FPQTtjQUtBO2NBTUE7Y0FNQTtjQUlBO2NBTUE7Y0FJQTtjQUlBO2NBS0E7OztDQXZEQTtDQUlBO0NBSUE7Q0FPQTtDQUtBO0NBTUE7Q0FNQTtDQUlBO0NBTUE7Q0FJQTtDQUlBO0NBS0E7Ozs7Q0F2REE7Q0FJQTtDQUlBO0NBT0E7Q0FLQTtDQU1BO0NBTUE7Q0FJQTtDQU1BO0NBSUE7Q0FJQTtDQUtBOzsifQ==
