/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const statusOk: string;

export {
	statusOk
};

declare const __default_export__: {
	statusOk: typeof statusOk;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidGlsa29tbWV0QWt0aXZpdGV0QWNjb3JkaW9uLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsidGlsa29tbWV0QWt0aXZpdGV0QWNjb3JkaW9uLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTs7O0NBQUE7Ozs7Q0FBQTs7In0=
