/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const table: string;

export { table };

declare const __default_export__: {
  table: typeof table;
};
export default __default_export__;
