/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const label: string;

export { container, label };

declare const __default_export__: {
  container: typeof container;
  label: typeof label;
};
export default __default_export__;
