/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const button: string;
declare const advarselIcon: string;
declare const feilmelding: string;

export {
	container,
	button,
	advarselIcon,
	feilmelding
};

declare const __default_export__: {
	container: typeof container;
	button: typeof button;
	advarselIcon: typeof advarselIcon;
	feilmelding: typeof feilmelding;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2VhcmNoRm9ybS5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbInNlYXJjaEZvcm0ubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBS007Y0FJTjtjQUNBOzs7Q0FWQTtDQUtNO0NBSU47Q0FDQTs7OztDQVZBO0NBS007Q0FJTjtDQUNBOzsifQ==
