/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const button: string;
declare const advarselIcon: string;
declare const feilmelding: string;

export {
	container,
	button,
	advarselIcon,
	feilmelding
};

declare const __default_export__: {
	container: typeof container;
	button: typeof button;
	advarselIcon: typeof advarselIcon;
	feilmelding: typeof feilmelding;
};
export default __default_export__;
