compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  navikt:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
