compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - "@navikt/*"
  - react-router@7.16.0
  - "@nais/apm@0.4.0"

npmScopes:
  nais:
    npmAlwaysAuth: true
    npmAuthToken: ghs_15368_eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRobmQiLCJjdHgiOiJhZGZWQ0luZ2JXRlZUWTMxTS1QWmNNc1lGczQtXzgxYzh5Wkl6VHFFc1dUc0hOZWRoU2NCM2ZZIiwiZXhwIjoxNzgzNTEzMTkwLCJpYXQiOjE3ODM1MDk1OTAsImlzcyI6ImdpdGh1YiIsImp0aSI6IjU4OWRiMzgxLTY0MzMtNDJlNy04M2NiLTdiODE5YjFjYTcwYSIsInZlciI6M30.w8u3NHIXlkpPmcgp229y2_JfMWbSYS2o-sc_gBnBMtsw57zzZ-IeFSzo8vYsTxpMvkXaSmwXy3j0JueUSeewbw
    npmRegistryServer: "https://npm.pkg.github.com"
  navikt:
    npmAlwaysAuth: true
    npmAuthToken: ghs_15368_eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRobmQiLCJjdHgiOiJhZGZWQ0luZ2JXRlZUWTMxTS1QWmNNc1lGczQtXzgxYzh5Wkl6VHFFc1dUc0hOZWRoU2NCM2ZZIiwiZXhwIjoxNzgzNTEzMTkwLCJpYXQiOjE3ODM1MDk1OTAsImlzcyI6ImdpdGh1YiIsImp0aSI6IjU4OWRiMzgxLTY0MzMtNDJlNy04M2NiLTdiODE5YjFjYTcwYSIsInZlciI6M30.w8u3NHIXlkpPmcgp229y2_JfMWbSYS2o-sc_gBnBMtsw57zzZ-IeFSzo8vYsTxpMvkXaSmwXy3j0JueUSeewbw
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.14.1.cjs
