compressionLevel: mixed

enableGlobalCache: false
enableScripts: false

nodeLinker: node-modules


npmPreapprovedPackages:
  - '@navikt/*'

npmScopes:
  navikt:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
