compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 7d

npmPreapprovedPackages:
  - "@navikt/*"

npmScopes:
  navikt:
    npmAlwaysAuth: true
    npmAuthToken: "${YARN_NPM_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  "eslint-plugin-react@*":
    peerDependencies:
      eslint: "^10.0.0"
  "eslint-plugin-react-hooks@*":
    peerDependencies:
      eslint: "^10.0.0"
  "eslint-plugin-jsx-a11y@*":
    peerDependencies:
      eslint: "^10.0.0"
  "@tanstack/eslint-plugin-query@*":
    peerDependencies:
      eslint: "^10.0.0"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
