compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - "@navikt/*"
  - react-router@7.16.0
  - "@nais/apm@0.4.0"

npmScopes:
  nais:
    npmAlwaysAuth: true
    npmAuthToken: ghs_15368_eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRobmQiLCJjdHgiOiI2cGxlSTZ3R3dDcmlrYUJaTWlZQVEwR0ZHdjc4SGxYRFZKSFExQlJvNzM0elhZdlhvenl4U2Q4IiwiZXhwIjoxNzg1ODQ1MjI2LCJpYXQiOjE3ODU4NDE2MjYsImlzcyI6ImdpdGh1YiIsImp0aSI6IjY0ZTZhNDc2LTE3NzQtNGRlNC1iZjhkLWE2Yzc3ODJiN2Y0ZCIsInZlciI6M30.onZMYYwkNuFV02nHYBluQ5G_V2EPgVckVv6y9F7UkLeb14TYND6T1xBtgENfH49CuD7QozOJOSFn0Sy_8gPDyg
    npmRegistryServer: "https://npm.pkg.github.com"
  navikt:
    npmAlwaysAuth: true
    npmAuthToken: ghs_15368_eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRobmQiLCJjdHgiOiI2cGxlSTZ3R3dDcmlrYUJaTWlZQVEwR0ZHdjc4SGxYRFZKSFExQlJvNzM0elhZdlhvenl4U2Q4IiwiZXhwIjoxNzg1ODQ1MjI2LCJpYXQiOjE3ODU4NDE2MjYsImlzcyI6ImdpdGh1YiIsImp0aSI6IjY0ZTZhNDc2LTE3NzQtNGRlNC1iZjhkLWE2Yzc3ODJiN2Y0ZCIsInZlciI6M30.onZMYYwkNuFV02nHYBluQ5G_V2EPgVckVv6y9F7UkLeb14TYND6T1xBtgENfH49CuD7QozOJOSFn0Sy_8gPDyg
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.14.1.cjs
