/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const begrunnelseTextField: string;
declare const explanationTextarea: string;
declare const explanationTextareaReadOnly: string;

export {
	begrunnelseTextField,
	explanationTextarea,
	explanationTextareaReadOnly
};

declare const __default_export__: {
	begrunnelseTextField: typeof begrunnelseTextField;
	explanationTextarea: typeof explanationTextarea;
	explanationTextareaReadOnly: typeof explanationTextareaReadOnly;
};
export default __default_export__;
