/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const begrunnelseTextField: string;
declare const explanationTextarea: string;
declare const explanationTextareaReadOnly: string;

export {
	begrunnelseTextField,
	explanationTextarea,
	explanationTextareaReadOnly
};

declare const __default_export__: {
	begrunnelseTextField: typeof begrunnelseTextField;
	explanationTextarea: typeof explanationTextarea;
	explanationTextareaReadOnly: typeof explanationTextareaReadOnly;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZmFrdGFCZWdydW5uZWxzZVRleHRGaWVsZC5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbImZha3RhQmVncnVubmVsc2VUZXh0RmllbGQubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBSUE7Y0FJQTs7O0NBUkE7Q0FJQTtDQUlBOzs7O0NBUkE7Q0FJQTtDQUlBOzsifQ==
