/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const vurdertIForrigeIcon: string;

export {
	vurdertIForrigeIcon
};

declare const __default_export__: {
	vurdertIForrigeIcon: typeof vurdertIForrigeIcon;
};
export default __default_export__;
