/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const vurdertIForrigeIcon: string;

export {
	vurdertIForrigeIcon
};

declare const __default_export__: {
	vurdertIForrigeIcon: typeof vurdertIForrigeIcon;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidnVyZGVydElGb3JyaWdlQmVoYW5kbGluZ0ljb24ubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJ2dXJkZXJ0SUZvcnJpZ2VCZWhhbmRsaW5nSWNvbi5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7OztDQUFBOzs7O0NBQUE7OyJ9
