/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const helpTextImage: string;
declare const tooltipContent: string;
declare const varsel: string;
declare const bold: string;

export {
	helpTextImage,
	tooltipContent,
	varsel,
	bold
};

declare const __default_export__: {
	helpTextImage: typeof helpTextImage;
	tooltipContent: typeof tooltipContent;
	varsel: typeof varsel;
	bold: typeof bold;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYXZyZWduaW5nUGFuZWwubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJhdnJlZ25pbmdQYW5lbC5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FJQTtjQVFBO2NBS0E7OztDQWpCQTtDQUlBO0NBUUE7Q0FLQTs7OztDQWpCQTtDQUlBO0NBUUE7Q0FLQTs7In0=
