/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const tableWrapper: string;
declare const tableTitle: string;
declare const simuleringTable: string;
declare const rodTekst: string;
declare const lastColumn: string;
declare const nextPeriod: string;
declare const normalPeriod: string;
declare const rowBorderSolid: string;
declare const rowBorderDashed: string;

export {
	tableWrapper,
	tableTitle,
	simuleringTable,
	rodTekst,
	lastColumn,
	nextPeriod,
	normalPeriod,
	rowBorderSolid,
	rowBorderDashed
};

declare const __default_export__: {
	tableWrapper: typeof tableWrapper;
	tableTitle: typeof tableTitle;
	simuleringTable: typeof simuleringTable;
	rodTekst: typeof rodTekst;
	lastColumn: typeof lastColumn;
	nextPeriod: typeof nextPeriod;
	normalPeriod: typeof normalPeriod;
	rowBorderSolid: typeof rowBorderSolid;
	rowBorderDashed: typeof rowBorderDashed;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYXZyZWduaW5nVGFibGUubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJhdnJlZ25pbmdUYWJsZS5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FNYztjQUlkO2NBS2lCO2NBSUE7Y0EyQ1M7Y0FNQTtjQVExQjtjQUlBOzs7Q0FoRkE7Q0FNYztDQUlkO0NBS2lCO0NBSUE7Q0EyQ1M7Q0FNQTtDQVExQjtDQUlBOzs7O0NBaEZBO0NBTWM7Q0FJZDtDQUtpQjtDQUlBO0NBMkNTO0NBTUE7Q0FRMUI7Q0FJQTs7In0=
