/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const tableWrapper: string;
declare const tableTitle: string;
declare const simuleringTable: string;
declare const rodTekst: string;
declare const lastColumn: string;
declare const nextPeriod: string;
declare const normalPeriod: string;
declare const rowBorderSolid: string;
declare const rowBorderDashed: string;

export {
	tableWrapper,
	tableTitle,
	simuleringTable,
	rodTekst,
	lastColumn,
	nextPeriod,
	normalPeriod,
	rowBorderSolid,
	rowBorderDashed
};

declare const __default_export__: {
	tableWrapper: typeof tableWrapper;
	tableTitle: typeof tableTitle;
	simuleringTable: typeof simuleringTable;
	rodTekst: typeof rodTekst;
	lastColumn: typeof lastColumn;
	nextPeriod: typeof nextPeriod;
	normalPeriod: typeof normalPeriod;
	rowBorderSolid: typeof rowBorderSolid;
	rowBorderDashed: typeof rowBorderDashed;
};
export default __default_export__;
