/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const helpTextImage: string;
declare const tooltipContent: string;
declare const varsel: string;
declare const bold: string;

export { helpTextImage, tooltipContent, varsel, bold };

declare const __default_export__: {
  helpTextImage: typeof helpTextImage;
  tooltipContent: typeof tooltipContent;
  varsel: typeof varsel;
  bold: typeof bold;
};
export default __default_export__;
