name: Setup + Install
description: Run commands needed to setup pnpm and install dependencies.
inputs:
  npmAuthToken:
    description: Token that has packages:read permission for the navikt organization
    required: true

runs:
  using: composite
  steps:
    - name: Sette opp pnpm
      uses: pnpm/action-setup@v4

    - name: Sette opp node
      uses: actions/setup-node@v6
      with:
        node-version: '22'
        cache: pnpm

    - name: Installere dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --ignore-scripts
      env:
        NPM_AUTH_TOKEN: ${{ inputs.npmAuthToken }}
