/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;

export {
	container
};

declare const __default_export__: {
	container: typeof container;
};
export default __default_export__;
