const aksjonspunktÅrsaker = {
  MANGLENDE_INNTEKTSMELDING: 'MANGLENDE_INNTEKTSMELDING',
  INNTEKTSMELDING_UTEN_ARBEIDSFORHOLD: 'INNTEKTSMELDING_UTEN_ARBEIDSFORHOLD',
  ENDRING_I_ARBEIDSFORHOLDS_ID: 'ENDRING_I_ARBEIDSFORHOLDS_ID',
  OVERGANG_ARBEIDSFORHOLDS_ID_UNDER_YTELSE: 'OVERGANG_ARBEIDSFORHOLDS_ID_UNDER_YTELSE',
};

export default aksjonspunktÅrsaker;
