/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const chatRight: string;

export { chatRight };

declare const __default_export__: {
  chatRight: typeof chatRight;
};
export default __default_export__;
