/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const chatRight: string;

export {
	chatRight
};

declare const __default_export__: {
	chatRight: typeof chatRight;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5uc2xhZ2JvYmxlLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsiaW5uc2xhZ2JvYmxlLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTs7O0NBQUE7Ozs7Q0FBQTs7In0=
