/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const starImage: string;
declare const resultatStatusImage: string;
declare const pushRight: string;
declare const pushRightCorner: string;
declare const line: string;
declare const arsakPadding: string;
declare const timePadding: string;
declare const resultatPadding: string;
declare const inline: string;
declare const firstColumnWidth: string;
declare const behandlingPicker: string;
declare const dateContainer: string;
declare const resultContainer: string;
declare const _pneText: string;
declare const _pneChevron: string;
declare const kalenderIcon: string;
declare const smallerUndertittel: string;
declare const utfallImage: string;
declare const indent: string;
declare const opprettetDatoContainer: string;

export {
	starImage,
	resultatStatusImage,
	pushRight,
	pushRightCorner,
	line,
	arsakPadding,
	timePadding,
	resultatPadding,
	inline,
	firstColumnWidth,
	behandlingPicker,
	dateContainer,
	resultContainer,
	kalenderIcon,
	smallerUndertittel,
	utfallImage,
	indent,
	opprettetDatoContainer
};

declare const __default_export__: {
	starImage: typeof starImage;
	resultatStatusImage: typeof resultatStatusImage;
	pushRight: typeof pushRight;
	pushRightCorner: typeof pushRightCorner;
	line: typeof line;
	arsakPadding: typeof arsakPadding;
	timePadding: typeof timePadding;
	resultatPadding: typeof resultatPadding;
	inline: typeof inline;
	firstColumnWidth: typeof firstColumnWidth;
	behandlingPicker: typeof behandlingPicker;
	dateContainer: typeof dateContainer;
	resultContainer: typeof resultContainer;
	"åpneText": typeof _pneText;
	"åpneChevron": typeof _pneChevron;
	kalenderIcon: typeof kalenderIcon;
	smallerUndertittel: typeof smallerUndertittel;
	utfallImage: typeof utfallImage;
	indent: typeof indent;
	opprettetDatoContainer: typeof opprettetDatoContainer;
};
export default __default_export__;
