/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const starImage: string;
declare const resultatStatusImage: string;
declare const pushRight: string;
declare const pushRightCorner: string;
declare const line: string;
declare const arsakPadding: string;
declare const timePadding: string;
declare const resultatPadding: string;
declare const inline: string;
declare const firstColumnWidth: string;
declare const behandlingPicker: string;
declare const dateContainer: string;
declare const resultContainer: string;
declare const _pneText: string;
declare const _pneChevron: string;
declare const kalenderIcon: string;
declare const smallerUndertittel: string;
declare const utfallImage: string;
declare const indent: string;
declare const opprettetDatoContainer: string;

export {
	starImage,
	resultatStatusImage,
	pushRight,
	pushRightCorner,
	line,
	arsakPadding,
	timePadding,
	resultatPadding,
	inline,
	firstColumnWidth,
	behandlingPicker,
	dateContainer,
	resultContainer,
	kalenderIcon,
	smallerUndertittel,
	utfallImage,
	indent,
	opprettetDatoContainer
};

declare const __default_export__: {
	starImage: typeof starImage;
	resultatStatusImage: typeof resultatStatusImage;
	pushRight: typeof pushRight;
	pushRightCorner: typeof pushRightCorner;
	line: typeof line;
	arsakPadding: typeof arsakPadding;
	timePadding: typeof timePadding;
	resultatPadding: typeof resultatPadding;
	inline: typeof inline;
	firstColumnWidth: typeof firstColumnWidth;
	behandlingPicker: typeof behandlingPicker;
	dateContainer: typeof dateContainer;
	resultContainer: typeof resultContainer;
	"åpneText": typeof _pneText;
	"åpneChevron": typeof _pneChevron;
	kalenderIcon: typeof kalenderIcon;
	smallerUndertittel: typeof smallerUndertittel;
	utfallImage: typeof utfallImage;
	indent: typeof indent;
	opprettetDatoContainer: typeof opprettetDatoContainer;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYmVoYW5kbGluZ1BpY2tlckl0ZW1Db250ZW50Lm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsiYmVoYW5kbGluZ1BpY2tlckl0ZW1Db250ZW50Lm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQU9BO2NBS0E7Y0FJQTtjQUtBO2NBTUE7Y0FJQTtjQUlBO2NBSUE7Y0FJQTtjQUlBO2NBTWtCO2NBS0E7Y0FTQTtjQU9BO2NBSUE7Y0FPQTtjQU1BO2NBT2xCO2NBS0E7OztDQXZHQTtDQU9BO0NBS0E7Q0FJQTtDQUtBO0NBTUE7Q0FJQTtDQUlBO0NBSUE7Q0FJQTtDQUlBO0NBTWtCO0NBS0E7Q0FvQkE7Q0FPQTtDQU1BO0NBT2xCO0NBS0E7Ozs7Q0F2R0E7Q0FPQTtDQUtBO0NBSUE7Q0FLQTtDQU1BO0NBSUE7Q0FJQTtDQUlBO0NBSUE7Q0FJQTtDQU1rQjtDQUtBOzs7Q0FvQkE7Q0FPQTtDQU1BO0NBT2xCO0NBS0E7OyJ9
