/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const behandlingPicker: string;
declare const backButton: string;
declare const behandlingList: string;
declare const linkToBehandling: string;
declare const toggleShowAllButton: string;
declare const headerContainer: string;

export {
	behandlingPicker,
	backButton,
	behandlingList,
	linkToBehandling,
	toggleShowAllButton,
	headerContainer
};

declare const __default_export__: {
	behandlingPicker: typeof behandlingPicker;
	backButton: typeof backButton;
	behandlingList: typeof behandlingList;
	linkToBehandling: typeof linkToBehandling;
	toggleShowAllButton: typeof toggleShowAllButton;
	headerContainer: typeof headerContainer;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYmVoYW5kbGluZ1BpY2tlci5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbImJlaGFuZGxpbmdQaWNrZXIubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBS2tCO2NBT2xCO2NBZ0JBO2NBQ0E7Y0ErQkE7OztDQTVEQTtDQUtrQjtDQU9sQjtDQWdCQTtDQUNBO0NBK0JBOzs7O0NBNURBO0NBS2tCO0NBT2xCO0NBZ0JBO0NBQ0E7Q0ErQkE7OyJ9
