/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const behandlingSelectedContainer: string;
declare const aapen: string;
declare const dateContainer: string;
declare const resultContainer: string;
declare const opprettet: string;
declare const opprettetIcon: string;
declare const opprettetTittel: string;
declare const opprettetDetails: string;
declare const timeline: string;
declare const opprettet_rsak: string;
declare const kalenderIcon: string;
declare const utfallImage: string;
declare const infoContainer: string;
declare const flexContainer: string;
declare const marginRight4: string;
declare const marginTop8: string;
declare const marginTop2: string;
declare const font18: string;
declare const _rsakerContainer: string;
declare const _rsakerList: string;
declare const faktapanelLenke: string;

export {
	behandlingSelectedContainer,
	aapen,
	dateContainer,
	resultContainer,
	opprettet,
	opprettetIcon,
	opprettetTittel,
	opprettetDetails,
	timeline,
	kalenderIcon,
	utfallImage,
	infoContainer,
	flexContainer,
	marginRight4,
	marginTop8,
	marginTop2,
	font18,
	faktapanelLenke
};

declare const __default_export__: {
	behandlingSelectedContainer: typeof behandlingSelectedContainer;
	aapen: typeof aapen;
	dateContainer: typeof dateContainer;
	resultContainer: typeof resultContainer;
	opprettet: typeof opprettet;
	opprettetIcon: typeof opprettetIcon;
	opprettetTittel: typeof opprettetTittel;
	opprettetDetails: typeof opprettetDetails;
	timeline: typeof timeline;
	"opprettetÅrsak": typeof opprettet_rsak;
	kalenderIcon: typeof kalenderIcon;
	utfallImage: typeof utfallImage;
	infoContainer: typeof infoContainer;
	flexContainer: typeof flexContainer;
	marginRight4: typeof marginRight4;
	marginTop8: typeof marginTop8;
	marginTop2: typeof marginTop2;
	font18: typeof font18;
	"årsakerContainer": typeof _rsakerContainer;
	"årsakerList": typeof _rsakerList;
	faktapanelLenke: typeof faktapanelLenke;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYmVoYW5kbGluZ1NlbGVjdGVkLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsiYmVoYW5kbGluZ1NlbGVjdGVkLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQVE0QjtjQUtDO2NBS0E7Y0FLQTtjQU9BO2NBYUE7Y0FLQTtjQUlBO2NBSUE7Y0FJQTtjQU9BO2NBT0E7Y0FNQTtjQUtBO2NBSUE7Y0FJQTtjQUlBO2NBSUE7Y0FJQTtjQW1DQTs7O0NBNUk3QjtDQVE0QjtDQUtDO0NBS0E7Q0FLQTtDQU9BO0NBYUE7Q0FLQTtDQUlBO0NBUUE7Q0FPQTtDQU9BO0NBTUE7Q0FLQTtDQUlBO0NBSUE7Q0FJQTtDQTJDQTs7OztDQTVJN0I7Q0FRNEI7Q0FLQztDQUtBO0NBS0E7Q0FPQTtDQWFBO0NBS0E7Q0FJQTs7Q0FRQTtDQU9BO0NBT0E7Q0FNQTtDQUtBO0NBSUE7Q0FJQTtDQUlBOzs7Q0EyQ0E7OyJ9
