/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const behandlingSelectedContainer: string;
declare const aapen: string;
declare const dateContainer: string;
declare const resultContainer: string;
declare const opprettet: string;
declare const opprettetIcon: string;
declare const opprettetTittel: string;
declare const opprettetDetails: string;
declare const timeline: string;
declare const opprettet_rsak: string;
declare const kalenderIcon: string;
declare const utfallImage: string;
declare const infoContainer: string;
declare const flexContainer: string;
declare const marginRight4: string;
declare const marginTop8: string;
declare const marginTop2: string;
declare const font18: string;
declare const _rsakerContainer: string;
declare const _rsakerList: string;
declare const faktapanelLenke: string;

export {
  behandlingSelectedContainer,
  aapen,
  dateContainer,
  resultContainer,
  opprettet,
  opprettetIcon,
  opprettetTittel,
  opprettetDetails,
  timeline,
  kalenderIcon,
  utfallImage,
  infoContainer,
  flexContainer,
  marginRight4,
  marginTop8,
  marginTop2,
  font18,
  faktapanelLenke,
};

declare const __default_export__: {
  behandlingSelectedContainer: typeof behandlingSelectedContainer;
  aapen: typeof aapen;
  dateContainer: typeof dateContainer;
  resultContainer: typeof resultContainer;
  opprettet: typeof opprettet;
  opprettetIcon: typeof opprettetIcon;
  opprettetTittel: typeof opprettetTittel;
  opprettetDetails: typeof opprettetDetails;
  timeline: typeof timeline;
  opprettetÅrsak: typeof opprettet_rsak;
  kalenderIcon: typeof kalenderIcon;
  utfallImage: typeof utfallImage;
  infoContainer: typeof infoContainer;
  flexContainer: typeof flexContainer;
  marginRight4: typeof marginRight4;
  marginTop8: typeof marginTop8;
  marginTop2: typeof marginTop2;
  font18: typeof font18;
  årsakerContainer: typeof _rsakerContainer;
  årsakerList: typeof _rsakerList;
  faktapanelLenke: typeof faktapanelLenke;
};
export default __default_export__;
