/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const behandlingPicker: string;
declare const backButton: string;
declare const behandlingList: string;
declare const linkToBehandling: string;
declare const toggleShowAllButton: string;
declare const headerContainer: string;

export { behandlingPicker, backButton, behandlingList, linkToBehandling, toggleShowAllButton, headerContainer };

declare const __default_export__: {
  behandlingPicker: typeof behandlingPicker;
  backButton: typeof backButton;
  behandlingList: typeof behandlingList;
  linkToBehandling: typeof linkToBehandling;
  toggleShowAllButton: typeof toggleShowAllButton;
  headerContainer: typeof headerContainer;
};
export default __default_export__;
