enum FagsakYtelseType {
  ENGANGSSTONAD = 'ES',
  FORELDREPENGER = 'FP',
  SVANGERSKAPSPENGER = 'SVP',
  PLEIEPENGER = 'PSB',
  OMSORGSPENGER = 'OMP',
  OMSORGSPENGER_MIDLERTIDIG_ALENE = 'OMP_MA',
  OMSORGSPENGER_KRONISK_SYKT_BARN = 'OMP_KS',
  OMSORGSPENGER_ALENE_OM_OMSORGEN = 'OMP_AO',
  FRISINN = 'FRISINN',
  PLEIEPENGER_SLUTTFASE = 'PPN',
  OPPLÆRINGSPENGER = 'OLP',
}

export default FagsakYtelseType;
