/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const timelineControlContatiner: string;
declare const upperTimeLine: string;
declare const scrollButtonContainer: string;
declare const controlButtonsContainer: string;
declare const buttonSpacing: string;
declare const popUnder: string;
declare const popUnderContent: string;
declare const timelineSokerContatiner: string;

export {
	timelineControlContatiner,
	upperTimeLine,
	scrollButtonContainer,
	controlButtonsContainer,
	buttonSpacing,
	popUnder,
	popUnderContent,
	timelineSokerContatiner
};

declare const __default_export__: {
	timelineControlContatiner: typeof timelineControlContatiner;
	upperTimeLine: typeof upperTimeLine;
	scrollButtonContainer: typeof scrollButtonContainer;
	controlButtonsContainer: typeof controlButtonsContainer;
	buttonSpacing: typeof buttonSpacing;
	popUnder: typeof popUnder;
	popUnderContent: typeof popUnderContent;
	timelineSokerContatiner: typeof timelineSokerContatiner;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidGltZUxpbmVDb250cm9sLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsidGltZUxpbmVDb250cm9sLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQVNBO2NBWUE7Y0FPQTtjQUlBO2NBS0E7Y0FLQTtjQXNERTs7O0NBaEdGO0NBU0E7Q0FZQTtDQU9BO0NBSUE7Q0FLQTtDQUtBO0NBc0RFOzs7O0NBaEdGO0NBU0E7Q0FZQTtDQU9BO0NBSUE7Q0FLQTtDQUtBO0NBc0RFOzsifQ==
