/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const timelineControlContatiner: string;
declare const upperTimeLine: string;
declare const scrollButtonContainer: string;
declare const controlButtonsContainer: string;
declare const buttonSpacing: string;
declare const popUnder: string;
declare const popUnderContent: string;
declare const timelineSokerContatiner: string;

export {
	timelineControlContatiner,
	upperTimeLine,
	scrollButtonContainer,
	controlButtonsContainer,
	buttonSpacing,
	popUnder,
	popUnderContent,
	timelineSokerContatiner
};

declare const __default_export__: {
	timelineControlContatiner: typeof timelineControlContatiner;
	upperTimeLine: typeof upperTimeLine;
	scrollButtonContainer: typeof scrollButtonContainer;
	controlButtonsContainer: typeof controlButtonsContainer;
	buttonSpacing: typeof buttonSpacing;
	popUnder: typeof popUnder;
	popUnderContent: typeof popUnderContent;
	timelineSokerContatiner: typeof timelineSokerContatiner;
};
export default __default_export__;
