/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const buttonLink: string;

export { buttonLink };

declare const __default_export__: {
  buttonLink: typeof buttonLink;
};
export default __default_export__;
