/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const tableStatusCell: string;
declare const selectableRow: string;
declare const selectedRow: string;

export {
	tableStatusCell,
	selectableRow,
	selectedRow
};

declare const __default_export__: {
	tableStatusCell: typeof tableStatusCell;
	selectableRow: typeof selectableRow;
	selectedRow: typeof selectedRow;
};
export default __default_export__;
