/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const tableStatusCell: string;
declare const selectableRow: string;
declare const selectedRow: string;

export {
	tableStatusCell,
	selectableRow,
	selectedRow
};

declare const __default_export__: {
	tableStatusCell: typeof tableStatusCell;
	selectableRow: typeof selectableRow;
	selectedRow: typeof selectedRow;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidmlsa8OlclNwbGl0dFBhbmVsLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsidmlsa8OlclNwbGl0dFBhbmVsLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQUtBO2NBSUE7OztDQVRBO0NBS0E7Q0FJQTs7OztDQVRBO0NBS0E7Q0FJQTs7In0=
