/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const vurderOverlappendeSak: string;
declare const apContainer: string;
declare const apActive: string;
declare const apReadOnly: string;
declare const uttaksgradField: string;
declare const uttaksgradPeriode: string;
declare const uttaksPeriodeEndret: string;
declare const vurderOverlappendeSakAPListe: string;
declare const noOverlappendeMargin: string;

export {
	vurderOverlappendeSak,
	apContainer,
	apActive,
	apReadOnly,
	uttaksgradField,
	uttaksgradPeriode,
	uttaksPeriodeEndret,
	vurderOverlappendeSakAPListe,
	noOverlappendeMargin
};

declare const __default_export__: {
	vurderOverlappendeSak: typeof vurderOverlappendeSak;
	apContainer: typeof apContainer;
	apActive: typeof apActive;
	apReadOnly: typeof apReadOnly;
	uttaksgradField: typeof uttaksgradField;
	uttaksgradPeriode: typeof uttaksgradPeriode;
	uttaksPeriodeEndret: typeof uttaksPeriodeEndret;
	vurderOverlappendeSakAPListe: typeof vurderOverlappendeSakAPListe;
	noOverlappendeMargin: typeof noOverlappendeMargin;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVnVyZGVyT3ZlcmxhcHBlbmRlU2FrLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsiVnVyZGVyT3ZlcmxhcHBlbmRlU2FrLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQUlBO2NBS0E7Y0FJQTtjQW1CQTtjQUlBO2NBVUE7Y0FJQTtjQUlBOzs7Q0F0REE7Q0FJQTtDQUtBO0NBSUE7Q0FtQkE7Q0FJQTtDQVVBO0NBSUE7Q0FJQTs7OztDQXREQTtDQUlBO0NBS0E7Q0FJQTtDQW1CQTtDQUlBO0NBVUE7Q0FJQTtDQUlBOzsifQ==
