/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const vurderOverlappendeSak: string;
declare const apContainer: string;
declare const apActive: string;
declare const apReadOnly: string;
declare const uttaksgradField: string;
declare const uttaksgradPeriode: string;
declare const uttaksPeriodeEndret: string;
declare const vurderOverlappendeSakAPListe: string;
declare const noOverlappendeMargin: string;

export {
	vurderOverlappendeSak,
	apContainer,
	apActive,
	apReadOnly,
	uttaksgradField,
	uttaksgradPeriode,
	uttaksPeriodeEndret,
	vurderOverlappendeSakAPListe,
	noOverlappendeMargin
};

declare const __default_export__: {
	vurderOverlappendeSak: typeof vurderOverlappendeSak;
	apContainer: typeof apContainer;
	apActive: typeof apActive;
	apReadOnly: typeof apReadOnly;
	uttaksgradField: typeof uttaksgradField;
	uttaksgradPeriode: typeof uttaksgradPeriode;
	uttaksPeriodeEndret: typeof uttaksPeriodeEndret;
	vurderOverlappendeSakAPListe: typeof vurderOverlappendeSakAPListe;
	noOverlappendeMargin: typeof noOverlappendeMargin;
};
export default __default_export__;
