/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const begrunnelseBoks: string;
declare const begrunnelseTekst: string;
declare const begrunnelseFooter: string;
declare const utbetalingsgrader: string;
declare const utbetalingsgrad: string;
declare const utbetalingsgradProsent: string;
declare const utbetalingsgradNavn: string;

export {
	begrunnelseBoks,
	begrunnelseTekst,
	begrunnelseFooter,
	utbetalingsgrader,
	utbetalingsgrad,
	utbetalingsgradProsent,
	utbetalingsgradNavn
};

declare const __default_export__: {
	begrunnelseBoks: typeof begrunnelseBoks;
	begrunnelseTekst: typeof begrunnelseTekst;
	begrunnelseFooter: typeof begrunnelseFooter;
	utbetalingsgrader: typeof utbetalingsgrader;
	utbetalingsgrad: typeof utbetalingsgrad;
	utbetalingsgradProsent: typeof utbetalingsgradProsent;
	utbetalingsgradNavn: typeof utbetalingsgradNavn;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYmVncnVubmVsc2VCb2tzLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsiYmVncnVubmVsc2VCb2tzLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQU1BO2NBUUE7Y0FjQTtjQU1BO2NBSUE7Y0FLQTs7O0NBM0NBO0NBTUE7Q0FRQTtDQWNBO0NBTUE7Q0FJQTtDQUtBOzs7O0NBM0NBO0NBTUE7Q0FRQTtDQWNBO0NBTUE7Q0FJQTtDQUtBOzsifQ==
