/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const begrunnelseBoks: string;
declare const begrunnelseTekst: string;
declare const begrunnelseFooter: string;
declare const utbetalingsgrader: string;
declare const utbetalingsgrad: string;
declare const utbetalingsgradProsent: string;
declare const utbetalingsgradNavn: string;

export {
  begrunnelseBoks,
  begrunnelseTekst,
  begrunnelseFooter,
  utbetalingsgrader,
  utbetalingsgrad,
  utbetalingsgradProsent,
  utbetalingsgradNavn,
};

declare const __default_export__: {
  begrunnelseBoks: typeof begrunnelseBoks;
  begrunnelseTekst: typeof begrunnelseTekst;
  begrunnelseFooter: typeof begrunnelseFooter;
  utbetalingsgrader: typeof utbetalingsgrader;
  utbetalingsgrad: typeof utbetalingsgrad;
  utbetalingsgradProsent: typeof utbetalingsgradProsent;
  utbetalingsgradNavn: typeof utbetalingsgradNavn;
};
export default __default_export__;
