/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const antallDagerLivetsSluttfaseContainer: string;
declare const header: string;
declare const sistePleiedagBoks: string;

export {
	antallDagerLivetsSluttfaseContainer,
	header,
	sistePleiedagBoks
};

declare const __default_export__: {
	antallDagerLivetsSluttfaseContainer: typeof antallDagerLivetsSluttfaseContainer;
	header: typeof header;
	sistePleiedagBoks: typeof sistePleiedagBoks;
};
export default __default_export__;
