/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const bakgrunnsBar: string;
declare const gronnBar: string;
declare const gulBar: string;
declare const antallTitler: string;

export {
	bakgrunnsBar,
	gronnBar,
	gulBar,
	antallTitler
};

declare const __default_export__: {
	bakgrunnsBar: typeof bakgrunnsBar;
	gronnBar: typeof gronnBar;
	gulBar: typeof gulBar;
	antallTitler: typeof antallTitler;
};
export default __default_export__;
