/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const bottomCell: string;
declare const rowWithSpacing: string;
declare const selectedCell: string;

export {
	bottomCell,
	rowWithSpacing,
	selectedCell
};

declare const __default_export__: {
	bottomCell: typeof bottomCell;
	rowWithSpacing: typeof rowWithSpacing;
	selectedCell: typeof selectedCell;
};
export default __default_export__;
