/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const bottomCell: string;
declare const rowWithSpacing: string;
declare const selectedCell: string;

export {
	bottomCell,
	rowWithSpacing,
	selectedCell
};

declare const __default_export__: {
	bottomCell: typeof bottomCell;
	rowWithSpacing: typeof rowWithSpacing;
	selectedCell: typeof selectedCell;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYWt0aXZpdGV0c3BlbmdlckJlcmVnbmluZy5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbImFrdGl2aXRldHNwZW5nZXJCZXJlZ25pbmcubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBS0E7Y0FVQTs7O0NBZkE7Q0FLQTtDQVVBOzs7O0NBZkE7Q0FLQTtDQVVBOzsifQ==
