/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const mainContainerWithSideMenu: string;
declare const warningIcon: string;
declare const vilkar: string;

export {
	mainContainerWithSideMenu,
	warningIcon,
	vilkar
};

declare const __default_export__: {
	mainContainerWithSideMenu: typeof mainContainerWithSideMenu;
	warningIcon: typeof warningIcon;
	vilkar: typeof vilkar;
};
export default __default_export__;
