/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const noSelectedBehandlingPanel: string;

export {
	noSelectedBehandlingPanel
};

declare const __default_export__: {
	noSelectedBehandlingPanel: typeof noSelectedBehandlingPanel;
};
export default __default_export__;
