const redusertUtbetalingArsak = {
  INNTEKT_REDUSERT_2019: 'INNTEKT_REDUSERT_2019',
  INNTEKT_I_SOKANDSPERIODE_ENDRET: 'INNTEKT_I_SØKNADSPERIODE_ENDRET',
  SOKNADSPERIODENS_LENGDE_ENDRET: 'SØKNADSPERIODENS_LENGDE_ENDRET',
};

export default redusertUtbetalingArsak;
