const redusertUtbetalingArsak = {
  INNTEKT_REDUSERT_2019: 'INNTEKT_REDUSERT_2019',
  INNTEKT_REDUSERT_2020_FOR_MARS: 'INNTEKT_REDUSERT_2020_FØR_MARS',
  INNTEKT_I_SOKANDSPERIODE_ENDRET: 'INNTEKT_I_SØKNADSPERIODE_ENDRET',
  SOKNADSPERIODENS_LENGDE_ENDRET: 'SØKNADSPERIODENS_LENGDE_ENDRET',
  DATO_FOR_NYOPPSTARTET_SN_ENDRET: 'DATO_FOR_NYOPPSTARTET_SN_ENDRET',
  SOKNAD_GJELDER_IKKE_LENGER_FL: 'SØKNAD_GJELDER_IKKE_LENGER_FL',
  SOKNAD_GJELDER_IKKE_LENGER_SN: 'SØKNAD_GJELDER_IKKE_LENGER_SN',
};

export default redusertUtbetalingArsak;
