const avslagsarsakCodes = {
  INGEN_BEREGNINGSREGLER: '1099',
  FOR_LAVT_BG: 'FOR_LAVT_BG',
  INGEN_FRILANS_I_PERIODE_UTEN_YTELSE: 'INGEN_FRILANS_I_PERIODE_UTEN_YTELSE',
  AVKORTET_GRUNNET_LØPENDE_INNTEKT: 'AVKORTET_GRUNNET_LØPENDE_INNTEKT',
  AVKORTET_GRUNNET_ANNEN_INNTEKT: 'AVKORTET_GRUNNET_ANNEN_INNTEKT',
};

export default avslagsarsakCodes;
