const fagsakYtelseType = {
  ENGANGSSTONAD: 'ES',
  FORELDREPENGER: 'FP',
  SVANGERSKAPSPENGER: 'SVP',
  PLEIEPENGER: 'PSB',
  OMSORGSPENGER: 'OMP',
  OMSORGSPENGER_KRONISK_SYKT_BARN: 'OMP_KS',
  FRISINN: 'FRISINN',
};

export default fagsakYtelseType;
