const inntektskategorier = {
  ARBEIDSTAKER: 'ARBEIDSTAKER',
  FRILANSER: 'FRILANSER',
  SELVSTENDIG_NÆRINGSDRIVENDE: 'SELVSTENDIG_NÆRINGSDRIVENDE',
  DAGPENGER: 'DAGPENGER',
  ARBEIDSAVKLARINGSPENGER: 'ARBEIDSAVKLARINGSPENGER',
  SJØMANN: 'SJØMANN',
  DAGMAMMA: 'DAGMAMMA',
  JORDBRUKER: 'JORDBRUKER',
  FISKER: 'FISKER',
  ARBEIDSTAKER_UTEN_FERIEPENGER: 'ARBEIDSTAKER_UTEN_FERIEPENGER',
  UDEFINERT: '-',
};

export default inntektskategorier;
