enum OpplysningAdresseType {
  BOSTEDSADRESSE = 'BOSTEDSADRESSE',
  POSTADRESSE = 'POSTADRESSE',
  UTENLANDSK_POSTADRESSE = 'POSTADRESSE_UTLAND',
  UTENLANDSK_NAV_TILLEGSADRESSE = 'MIDLERTIDIG_POSTADRESSE_UTLAND',
  UKJENT = 'UKJENT_ADRESSE',
}

export default OpplysningAdresseType;
