import { opptjeningAktivitetType as opptjeningAktivitetTypeV2 } from '@k9-sak-web/backend/k9sak/kodeverk/OpptjeningAktivitetType.js';

const opptjeningAktivitetType: typeof opptjeningAktivitetTypeV2 = {
  ARBEID: 'ARBEID',
  AAP: 'AAP',
  DAGPENGER: 'DAGPENGER',
  FORELDREPENGER: 'FORELDREPENGER',
  FRILANS: 'FRILANS',
  MILITÆR_ELLER_SIVILTJENESTE: 'MILITÆR_ELLER_SIVILTJENESTE',
  NÆRING: 'NÆRING',
  OMSORGSPENGER: 'OMSORGSPENGER',
  OPPLÆRINGSPENGER: 'OPPLÆRINGSPENGER',
  PLEIEPENGER: 'PLEIEPENGER',
  SVANGERSKAPSPENGER: 'SVANGERSKAPSPENGER',
  SYKEPENGER: 'SYKEPENGER',
  VIDERE_ETTERUTDANNING: 'VIDERE_ETTERUTDANNING',
  UTENLANDSK_ARBEIDSFORHOLD: 'UTENLANDSK_ARBEIDSFORHOLD',
  VENTELØNN_VARTPENGER: 'VENTELØNN_VARTPENGER',
  ETTERLØNN_SLUTTPAKKE: 'ETTERLØNN_SLUTTPAKKE',
  SYKEPENGER_AV_DAGPENGER: 'SYKEPENGER_AV_DAGPENGER',
  PLEIEPENGER_AV_DAGPENGER: 'PLEIEPENGER_AV_DAGPENGER',
  FRISINN: 'FRISINN',
  MELLOM_ARBEID: 'MELLOM_ARBEID',
  UTDANNINGSPERMISJON: 'UTDANNINGSPERMISJON',
  '-': '-',
};

export default opptjeningAktivitetType;
