const periodeAarsak = {
  NATURALYTELSE_BORTFALT: 'NATURALYTELSE_BORTFALT',
  ARBEIDSFORHOLD_AVSLUTTET: 'ARBEIDSFORHOLD_AVSLUTTET',
  NATURALYTELSE_TILKOMMER: 'NATURALYTELSE_TILKOMMER',
  ENDRING_I_REFUSJONSKRAV: 'ENDRING_I_REFUSJONSKRAV',
  REFUSJON_OPPHOERER: 'REFUSJON_OPPHØRER',
  GRADERING: 'GRADERING',
  GRADERING_OPPHOERER: 'GRADERING_OPPHØRER',
  ENDRING_I_AKTIVITETER_SØKT_FOR: 'ENDRING_I_AKTIVITETER_SØKT_FOR',
  UDEFINERT: '-',
};

export default periodeAarsak;
