const vilkarType = {
  OMSORGENFORVILKARET: 'K9_VK_1',
  // OMSORGENFORVILKARET: 'PSB_VK_1',
  MEDLEMSKAPSVILKARET: 'FP_VK_2',
  MEDISINSKVILKARET: 'K9_VK_2_a',
  // MEDISINSKVILKARET: 'PSB_VK_2_a',
  ALDERSVILKARET: 'K9_VK_3',
  SOKNADSFRISTVILKARET: 'FP_VK_3',
  OPPTJENINGSVILKARET: 'FP_VK_23',
  SOKERSOPPLYSNINGSPLIKT: 'FP_VK_34',
  BEREGNINGSGRUNNLAGVILKARET: 'FP_VK_41',
  UNNTAKSVILKARET: 'K9_VILKÅRET',
};

export default vilkarType;
