const vilkarType = {
  MEDLEMSKAPSVILKARET: 'FP_VK_2',
  OPPTJENINGSVILKARET: 'FP_VK_23',
  SOKERSOPPLYSNINGSPLIKT: 'FP_VK_34',
  BEREGNINGSGRUNNLAGVILKARET: 'FP_VK_41',
  MEDISINSKVILKARET: 'PSB_VK_2_a',
  OMSORGENFORVILKARET: 'PSB_VK_1',
  UNNTAKSVILKARET: 'K9_VILKÅRET',
};

export default vilkarType;
