const vilkarType = {
  OMSORGENFORVILKARET: 'K9_VK_1',
  MEDLEMSKAPSVILKARET: 'FP_VK_2',
  MEDISINSKEVILKÅR_UNDER_18_ÅR: 'K9_VK_2_a',
  MEDISINSKEVILKÅR_18_ÅR: 'K9_VK_2_b',
  ALDERSVILKARET: 'K9_VK_3',
  SOKNADSFRISTVILKARET: 'FP_VK_3',
  OPPTJENINGSVILKARET: 'FP_VK_23',
  SOKERSOPPLYSNINGSPLIKT: 'FP_VK_34',
  BEREGNINGSGRUNNLAGVILKARET: 'FP_VK_41',
  UNNTAKSVILKARET: 'K9_VILKÅRET',
  UTVIDETRETTVILKARET: 'K9_VK_9_6',
  OMP_OMSORGENFORVILKARET: 'K9_VK_1',
  PLEIEPENGER_LIVETS_SLUTTFASE: 'K9_VK_16',
  ALDERSVILKAR_BARN: 'K9_VK_5_3',
};

export default vilkarType;
