/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const oppgaveLenke: string;
declare const marginTop: string;

export {
	oppgaveLenke,
	marginTop
};

declare const __default_export__: {
	oppgaveLenke: typeof oppgaveLenke;
	marginTop: typeof marginTop;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHVuc2pzdHJpcGUubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJwdW5zanN0cmlwZS5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FJQTs7O0NBSkE7Q0FJQTs7OztDQUpBO0NBSUE7OyJ9
