export enum KodeverkTilbakeType {
  TILBAKEKR_VIDERE_BEH = 'VidereBehandling',
  SKJERMLENKE_TYPE = 'SkjermlenkeType',
  HENDELSE_TYPE = 'HendelseType',
  HENDELSE_UNDERTYPE = 'HendelseUnderType',
  HISTORIKKINNSLAG_TYPE = 'HistorikkinnslagType',
  VILKAAR_RESULTAT = 'VilkårResultat',
  HISTORIKK_OPPLYSNING_TYPE = 'HistorikkOpplysningType',
  VENT_AARSAK = 'Venteårsak',
  FORELDELSE_VURDERING = 'ForeldelseVurderingType',
  VURDERING = 'AnnenVurdering',
  AKTSOMHET = 'Aktsomhet',
  BEHANDLING_RESULTAT_TYPE = 'BehandlingResultatType',
  VURDER_AARSAK = 'VurderÅrsak',
  BEHANDLING_AARSAK = 'BehandlingÅrsakType',
  VERGE_TYPE = 'VergeType',
  VEDTAK_RESULTAT_TYPE = 'VedtakResultatType',
  BEHANDLING_TYPE = 'BehandlingType',
  HISTORIKK_AKTOER = 'HistorikkAktør',
  SAERLIG_GRUNN = 'SærligGrunn',
  HISTORIKK_ENDRET_FELT_TYPE = 'HistorikkEndretFeltType',
  FAGSYSTEM = 'Fagsystem',
}
