/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const halfColumn: string;
declare const fullWidth: string;
declare const approvalItemContainer: string;
declare const aksjonspunktTextContainer: string;
declare const lenke: string;

export {
	halfColumn,
	fullWidth,
	approvalItemContainer,
	aksjonspunktTextContainer,
	lenke
};

declare const __default_export__: {
	halfColumn: typeof halfColumn;
	fullWidth: typeof fullWidth;
	approvalItemContainer: typeof approvalItemContainer;
	aksjonspunktTextContainer: typeof aksjonspunktTextContainer;
	lenke: typeof lenke;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYWtzam9uc3B1bmt0R29ka2plbm5pbmdGaWVsZEFycmF5Lm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsiYWtzam9uc3B1bmt0R29ka2plbm5pbmdGaWVsZEFycmF5Lm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQUlBO2NBSUE7Y0FJQTtjQUlBOzs7Q0FoQkE7Q0FJQTtDQUlBO0NBSUE7Q0FJQTs7OztDQWhCQTtDQUlBO0NBSUE7Q0FJQTtDQUlBOzsifQ==
