/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const halfColumn: string;
declare const fullWidth: string;
declare const approvalItemContainer: string;
declare const aksjonspunktTextContainer: string;
declare const lenke: string;

export {
	halfColumn,
	fullWidth,
	approvalItemContainer,
	aksjonspunktTextContainer,
	lenke
};

declare const __default_export__: {
	halfColumn: typeof halfColumn;
	fullWidth: typeof fullWidth;
	approvalItemContainer: typeof approvalItemContainer;
	aksjonspunktTextContainer: typeof aksjonspunktTextContainer;
	lenke: typeof lenke;
};
export default __default_export__;
