/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const buttonRow: string;
declare const buttonLink: string;
declare const infoIkkeVedtaksbrev: string;

export {
	buttonRow,
	buttonLink,
	infoIkkeVedtaksbrev
};

declare const __default_export__: {
	buttonRow: typeof buttonRow;
	buttonLink: typeof buttonLink;
	infoIkkeVedtaksbrev: typeof infoIkkeVedtaksbrev;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidG90cmlubnNrb250cm9sbEJlc2x1dHRlckZvcm0ubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJ0b3RyaW5uc2tvbnRyb2xsQmVzbHV0dGVyRm9ybS5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FRQTtjQVNBOzs7Q0FqQkE7Q0FRQTtDQVNBOzs7O0NBakJBO0NBUUE7Q0FTQTs7In0=
