/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const image: string;
declare const approvalItem: string;
declare const approvalItemContainer: string;
declare const aksjonspunktTextContainer: string;
declare const resultatFraGodkjenningTextContainer: string;
declare const lenke: string;

export {
	image,
	approvalItem,
	approvalItemContainer,
	aksjonspunktTextContainer,
	resultatFraGodkjenningTextContainer,
	lenke
};

declare const __default_export__: {
	image: typeof image;
	approvalItem: typeof approvalItem;
	approvalItemContainer: typeof approvalItemContainer;
	aksjonspunktTextContainer: typeof aksjonspunktTextContainer;
	resultatFraGodkjenningTextContainer: typeof resultatFraGodkjenningTextContainer;
	lenke: typeof lenke;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidG90cmlubnNrb250cm9sbFNha3NiZWhhbmRsZXJQYW5lbC5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbInRvdHJpbm5za29udHJvbGxTYWtzYmVoYW5kbGVyUGFuZWwubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBTUE7Y0FNQTtjQUlBO2NBS0E7Y0FJQTs7O0NBekJBO0NBTUE7Q0FNQTtDQUlBO0NBS0E7Q0FJQTs7OztDQXpCQTtDQU1BO0NBTUE7Q0FJQTtDQUtBO0NBSUE7OyJ9
