/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const image: string;
declare const approvalItem: string;
declare const approvalItemContainer: string;
declare const aksjonspunktTextContainer: string;
declare const resultatFraGodkjenningTextContainer: string;
declare const lenke: string;

export {
	image,
	approvalItem,
	approvalItemContainer,
	aksjonspunktTextContainer,
	resultatFraGodkjenningTextContainer,
	lenke
};

declare const __default_export__: {
	image: typeof image;
	approvalItem: typeof approvalItem;
	approvalItemContainer: typeof approvalItemContainer;
	aksjonspunktTextContainer: typeof aksjonspunktTextContainer;
	resultatFraGodkjenningTextContainer: typeof resultatFraGodkjenningTextContainer;
	lenke: typeof lenke;
};
export default __default_export__;
