import type { folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_BeregningsgrunnlagPrStatusOgAndelDto } from '@k9-sak-web/backend/k9sak/generated/types.js';

export type BeregningsgrunnlagPrStatusOgAndelDto = folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_BeregningsgrunnlagPrStatusOgAndelDto;
