import type { folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_YtelsespesifiktGrunnlagDto } from '@k9-sak-web/backend/k9sak/generated/types.js';

export type YtelsespesifiktGrunnlagDto = folketrygdloven_kalkulus_response_v1_beregningsgrunnlag_gui_YtelsespesifiktGrunnlagDto;
