/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const stepArrowContainer: string;

export {
	stepArrowContainer
};

declare const __default_export__: {
	stepArrowContainer: typeof stepArrowContainer;
};
export default __default_export__;
