/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const stepArrowContainer: string;

export {
	stepArrowContainer
};

declare const __default_export__: {
	stepArrowContainer: typeof stepArrowContainer;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHJvc2Vzc01lbnkubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJwcm9zZXNzTWVueS5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7OztDQUFBOzs7O0NBQUE7OyJ9
