export type {
  ung_sak_kontrakt_aktivitetspenger_vilkår_BostedGrunnlagPeriodeDto as BostedGrunnlagPeriodeDto,
  ung_sak_kontrakt_aktivitetspenger_vilkår_BostedGrunnlagResponseDto as BostedGrunnlagResponseDto,
  ung_sak_kontrakt_aktivitetspenger_vilkår_bosted_VilkårBostedPeriodeVurderingDto as VilkårBostedPeriodeVurderingDto,
} from '@k9-sak-web/backend/ungsak/generated/types.js';
