/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const status: string;
declare const key: string;
declare const keyWithoutCursor: string;
declare const vilkar: string;
declare const aksjonspunktBox: string;
declare const aksjonspunktBoxOpen: string;

export {
	status,
	key,
	keyWithoutCursor,
	vilkar,
	aksjonspunktBox,
	aksjonspunktBoxOpen
};

declare const __default_export__: {
	status: typeof status;
	key: typeof key;
	keyWithoutCursor: typeof keyWithoutCursor;
	vilkar: typeof vilkar;
	aksjonspunktBox: typeof aksjonspunktBox;
	aksjonspunktBoxOpen: typeof aksjonspunktBoxOpen;
};
export default __default_export__;
