/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const status: string;
declare const key: string;
declare const keyWithoutCursor: string;
declare const vilkar: string;
declare const aksjonspunktBox: string;
declare const aksjonspunktBoxOpen: string;

export {
	status,
	key,
	keyWithoutCursor,
	vilkar,
	aksjonspunktBox,
	aksjonspunktBoxOpen
};

declare const __default_export__: {
	status: typeof status;
	key: typeof key;
	keyWithoutCursor: typeof keyWithoutCursor;
	vilkar: typeof vilkar;
	aksjonspunktBox: typeof aksjonspunktBox;
	aksjonspunktBoxOpen: typeof aksjonspunktBoxOpen;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidmlsa2FycmVzdWx0YXRNZWRPdmVyc3R5cmluZ0Zvcm1QZXJpb2Rpc2VydC5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbInZpbGthcnJlc3VsdGF0TWVkT3ZlcnN0eXJpbmdGb3JtUGVyaW9kaXNlcnQubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBS0E7Y0FNQTtjQUtBO2NBSUE7Y0FJQTs7O0NBeEJBO0NBS0E7Q0FNQTtDQUtBO0NBSUE7Q0FJQTs7OztDQXhCQTtDQUtBO0NBTUE7Q0FLQTtDQUlBO0NBSUE7OyJ9
