/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const modal: string;
declare const button: string;
declare const forhandsvis: string;

export { modal, button, forhandsvis };

declare const __default_export__: {
  modal: typeof modal;
  button: typeof button;
  forhandsvis: typeof forhandsvis;
};
export default __default_export__;
