/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const button: string;
declare const divider: string;
declare const image: string;
declare const modal: string;

export {
	button,
	divider,
	image,
	modal
};

declare const __default_export__: {
	button: typeof button;
	divider: typeof divider;
	image: typeof image;
	modal: typeof modal;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaGVubGFndEJlaGFuZGxpbmdNb2RhbC5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbImhlbmxhZ3RCZWhhbmRsaW5nTW9kYWwubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBSUE7Y0FXQTtjQU1BOzs7Q0FyQkE7Q0FJQTtDQVdBO0NBTUE7Ozs7Q0FyQkE7Q0FJQTtDQVdBO0NBTUE7OyJ9
