/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const button: string;
declare const divider: string;
declare const image: string;
declare const modal: string;

export {
	button,
	divider,
	image,
	modal
};

declare const __default_export__: {
	button: typeof button;
	divider: typeof divider;
	image: typeof image;
	modal: typeof modal;
};
export default __default_export__;
