/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const indicatorWithOverlay: string;
declare const indicator: string;
declare const overlay: string;

export { indicatorWithOverlay, indicator, overlay };

declare const __default_export__: {
  indicatorWithOverlay: typeof indicatorWithOverlay;
  indicator: typeof indicator;
  overlay: typeof overlay;
};
export default __default_export__;
