/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const indicatorWithOverlay: string;
declare const indicator: string;
declare const overlay: string;

export {
	indicatorWithOverlay,
	indicator,
	overlay
};

declare const __default_export__: {
	indicatorWithOverlay: typeof indicatorWithOverlay;
	indicator: typeof indicator;
	overlay: typeof overlay;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kaWNhdG9yV2l0aE92ZXJsYXkubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJpbmRpY2F0b3JXaXRoT3ZlcmxheS5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FLQTtjQVFBOzs7Q0FiQTtDQUtBO0NBUUE7Ozs7Q0FiQTtDQUtBO0NBUUE7OyJ9
