import type { BehandlingÅrsakDto } from '../../generated';
export type BehandlingÅrsakType = BehandlingÅrsakDto['behandlingArsakType'];

type BehandlingÅrsakTypeName =
  | 'FEIL_I_LOVANDVENDELSE'
  | 'FEIL_REGELVERKSFORSTAELSE'
  | 'FEIL_ELLER_ENDRET_FAKTA'
  | 'FEIL_PROSESSUELL'
  | 'ETTER_KLAGE'
  | 'ANNET'
  | 'KLAGE_U_INNTK'
  | 'KLAGE_M_INNTK'
  | 'MEDLEMSKAP'
  | 'OPPTJENING'
  | 'FORDELING'
  | 'INNTEKT'
  | 'DØD'
  | 'SØKERS_RELASJON'
  | 'SØKNADSFRIST'
  | 'BEREEGNINGSGRUNNLAG'
  | 'RE_TILSTØTENDE_YTELSE_INNVILGET'
  | 'RE_ENDRING_BEREGNINGSGRUNNLAG'
  | 'RE_TILSTØTENDE_YTELSE_OPPHØRT'
  | 'RE_ENDRING_FRA_BRUKER'
  | 'RE_ENDRET_INNTEKTSMELDING'
  | 'UNNT_GENERELL';

export const behandlingÅrsakType: Readonly<Record<BehandlingÅrsakTypeName, BehandlingÅrsakType>> = {
  FEIL_I_LOVANDVENDELSE: 'RE-LOV',
  FEIL_REGELVERKSFORSTAELSE: 'RE-RGLF',
  FEIL_ELLER_ENDRET_FAKTA: 'RE-FEFAKTA',
  FEIL_PROSESSUELL: 'RE-PRSSL',
  ETTER_KLAGE: 'ETTER_KLAGE',
  ANNET: 'RE-ANNET',
  KLAGE_U_INNTK: 'RE-KLAG-U-INNTK',
  KLAGE_M_INNTK: 'RE-KLAG-M-INNTK',
  MEDLEMSKAP: 'RE-MDL',
  OPPTJENING: 'RE-OPTJ',
  FORDELING: 'RE-FRDLING',
  INNTEKT: 'RE-INNTK',
  DØD: 'RE-DØD',
  SØKERS_RELASJON: 'RE-SRTB',
  SØKNADSFRIST: 'RE-FRIST',
  BEREEGNINGSGRUNNLAG: 'RE-BER-GRUN',
  RE_TILSTØTENDE_YTELSE_INNVILGET: 'RE-TILST-YT-INNVIL',
  RE_ENDRING_BEREGNINGSGRUNNLAG: 'RE-ENDR-BER-GRUN',
  RE_TILSTØTENDE_YTELSE_OPPHØRT: 'RE-TILST-YT-OPPH',
  RE_ENDRING_FRA_BRUKER: 'RE-END-FRA-BRUKER',
  RE_ENDRET_INNTEKTSMELDING: 'RE-END-INNTEKTSMELD',
  UNNT_GENERELL: 'UNNT_GENERELL',
};
