import type { VilkårDto } from '@navikt/k9-sak-typescript-client';

export type VilkarType = Exclude<VilkårDto['vilkarType'], undefined>;

export type VilkarTypeName =
  | 'OMSORGENFORVILKARET'
  | 'MEDLEMSKAPSVILKARET'
  | 'MEDISINSKEVILKÅR_UNDER_18_ÅR'
  | 'MEDISINSKEVILKÅR_18_ÅR'
  | 'ALDERSVILKARET'
  | 'SOKNADSFRISTVILKARET'
  | 'OPPTJENINGSVILKARET'
  | 'SOKERSOPPLYSNINGSPLIKT'
  | 'BEREGNINGSGRUNNLAGVILKARET'
  | 'UNNTAKSVILKARET'
  | 'UTVIDETRETTVILKARET'
  | 'OMP_OMSORGENFORVILKARET'
  | 'PLEIEPENGER_LIVETS_SLUTTFASE'
  | 'ALDERSVILKAR_BARN'
  | 'LANGVARIG_SYKDOM'
  | 'NØDVENDIG_OPPLÆRING'
  | 'GODKJENT_OPPLÆRINGSINSTITUSJON'
  | 'GJENNOMGÅ_OPPLÆRING'
  | 'UNGDOMSPROGRAMVILKARET';

export const vilkarType: Readonly<Record<VilkarTypeName, string>> = {
  OMSORGENFORVILKARET: 'K9_VK_1',
  MEDLEMSKAPSVILKARET: 'FP_VK_2',
  MEDISINSKEVILKÅR_UNDER_18_ÅR: 'K9_VK_2_a',
  MEDISINSKEVILKÅR_18_ÅR: 'K9_VK_2_b',
  ALDERSVILKARET: 'K9_VK_3',
  SOKNADSFRISTVILKARET: 'FP_VK_3',
  OPPTJENINGSVILKARET: 'FP_VK_23',
  SOKERSOPPLYSNINGSPLIKT: 'FP_VK_34',
  BEREGNINGSGRUNNLAGVILKARET: 'FP_VK_41',
  UNNTAKSVILKARET: 'K9_VILKÅRET',
  UTVIDETRETTVILKARET: 'K9_VK_9_6',
  OMP_OMSORGENFORVILKARET: 'K9_VK_1',
  PLEIEPENGER_LIVETS_SLUTTFASE: 'K9_VK_16',
  ALDERSVILKAR_BARN: 'K9_VK_5_3',
  LANGVARIG_SYKDOM: 'K9_VK_17',
  NØDVENDIG_OPPLÆRING: 'K9_VK_20',
  GODKJENT_OPPLÆRINGSINSTITUSJON: 'K9_VK_21',
  GJENNOMGÅ_OPPLÆRING: 'K9_VK_22',
  UNGDOMSPROGRAMVILKARET: 'UNG_VK_XXX',
};
