/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const orgnumField: string;
declare const orgnameField: string;
declare const errorField: string;

export {
	container,
	orgnumField,
	orgnameField,
	errorField
};

declare const __default_export__: {
	container: typeof container;
	orgnumField: typeof orgnumField;
	orgnameField: typeof orgnameField;
	errorField: typeof errorField;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVHJlZGplcGFydHNtb3R0YWtlcklucHV0Lm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsiVHJlZGplcGFydHNtb3R0YWtlcklucHV0Lm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQVdBO2NBSUE7Y0FJQTs7O0NBbkJBO0NBV0E7Q0FJQTtDQUlBOzs7O0NBbkJBO0NBV0E7Q0FJQTtDQUlBOzsifQ==
