/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const utsattePerioderStripe: string;
declare const punktliste: string;
declare const bodyText: string;

export {
	utsattePerioderStripe,
	punktliste,
	bodyText
};

declare const __default_export__: {
	utsattePerioderStripe: typeof utsattePerioderStripe;
	punktliste: typeof punktliste;
	bodyText: typeof bodyText;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidXRzYXR0ZVBlcmlvZGVyU3RyaXBlLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsidXRzYXR0ZVBlcmlvZGVyU3RyaXBlLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQVN1QjtjQUtBOzs7Q0FkdkI7Q0FTdUI7Q0FLQTs7OztDQWR2QjtDQVN1QjtDQUtBOzsifQ==
