/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const divider: string;
declare const image: string;
declare const oneElement: string;
declare const aksjonspunktText: string;
declare const wordwrap: string;

export {
	container,
	divider,
	image,
	oneElement,
	aksjonspunktText,
	wordwrap
};

declare const __default_export__: {
	container: typeof container;
	divider: typeof divider;
	image: typeof image;
	oneElement: typeof oneElement;
	aksjonspunktText: typeof aksjonspunktText;
	wordwrap: typeof wordwrap;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidGlsYmFrZXRyZWtrcGFuZWwubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJ0aWxiYWtldHJla2twYW5lbC5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FJQTtjQVNBO2NBTUE7Y0FLQTtjQUtBOzs7Q0E3QkE7Q0FJQTtDQVNBO0NBTUE7Q0FLQTtDQUtBOzs7O0NBN0JBO0NBSUE7Q0FTQTtDQU1BO0NBS0E7Q0FLQTs7In0=
