/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const nyttNotatTekst: string;
declare const nyttNotatKnappContainer: string;
declare const notatContainer: string;
declare const labelTagContainer: string;
declare const redigerSkjulNotatKnappContainer: string;
declare const redigerSkjulKnapp: string;
declare const navnTag: string;
declare const chatRight: string;
declare const chatLeft: string;

export {
	nyttNotatTekst,
	nyttNotatKnappContainer,
	notatContainer,
	labelTagContainer,
	redigerSkjulNotatKnappContainer,
	redigerSkjulKnapp,
	navnTag,
	chatRight,
	chatLeft
};

declare const __default_export__: {
	nyttNotatTekst: typeof nyttNotatTekst;
	nyttNotatKnappContainer: typeof nyttNotatKnappContainer;
	notatContainer: typeof notatContainer;
	labelTagContainer: typeof labelTagContainer;
	redigerSkjulNotatKnappContainer: typeof redigerSkjulNotatKnappContainer;
	redigerSkjulKnapp: typeof redigerSkjulKnapp;
	navnTag: typeof navnTag;
	chatRight: typeof chatRight;
	chatLeft: typeof chatLeft;
};
export default __default_export__;
