/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const nyttNotatTekst: string;
declare const nyttNotatKnappContainer: string;
declare const notatContainer: string;
declare const labelTagContainer: string;
declare const redigerSkjulNotatKnappContainer: string;
declare const redigerSkjulKnapp: string;
declare const navnTag: string;
declare const chatRight: string;
declare const chatLeft: string;

export {
	nyttNotatTekst,
	nyttNotatKnappContainer,
	notatContainer,
	labelTagContainer,
	redigerSkjulNotatKnappContainer,
	redigerSkjulKnapp,
	navnTag,
	chatRight,
	chatLeft
};

declare const __default_export__: {
	nyttNotatTekst: typeof nyttNotatTekst;
	nyttNotatKnappContainer: typeof nyttNotatKnappContainer;
	notatContainer: typeof notatContainer;
	labelTagContainer: typeof labelTagContainer;
	redigerSkjulNotatKnappContainer: typeof redigerSkjulNotatKnappContainer;
	redigerSkjulKnapp: typeof redigerSkjulKnapp;
	navnTag: typeof navnTag;
	chatRight: typeof chatRight;
	chatLeft: typeof chatLeft;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY2hhdENvbXBvbmVudC5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbImNoYXRDb21wb25lbnQubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBSUE7Y0FPQTtjQU9BO2NBS0E7Y0FJc0I7Y0FJSDtjQUluQjtjQUtFOzs7Q0F4Q0Y7Q0FJQTtDQU9BO0NBT0E7Q0FLQTtDQUlzQjtDQUlIO0NBSW5CO0NBS0U7Ozs7Q0F4Q0Y7Q0FJQTtDQU9BO0NBT0E7Q0FLQTtDQUlzQjtDQUlIO0NBSW5CO0NBS0U7OyJ9
