import { AbacKlageVurderingResultatAksjonspunktMellomlagringDtoKlageVurdering } from '@navikt/k9-klage-typescript-client/types';

export type KlagevurderingType = AbacKlageVurderingResultatAksjonspunktMellomlagringDtoKlageVurdering;
export const Klagevurdering = AbacKlageVurderingResultatAksjonspunktMellomlagringDtoKlageVurdering;
