/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const periodeContainer: string;
declare const relative: string;
declare const addArbeidsforhold: string;
declare const oppdaterMargin: string;
declare const suffix: string;
declare const textAlignRight: string;
declare const alignRightHorizontalBottom: string;
declare const fieldHorizontal: string;
declare const modalLabel: string;
declare const iconContainer: string;
declare const icon: string;
declare const fullWidth: string;
declare const modal: string;
declare const textAreaStyle: string;
declare const right: string;
declare const button: string;
declare const buttonRemove: string;
declare const buttonAdd: string;
declare const addCircleIcon: string;
declare const imageText: string;
declare const addPeriode: string;

export {
  periodeContainer,
  relative,
  addArbeidsforhold,
  oppdaterMargin,
  suffix,
  textAlignRight,
  alignRightHorizontalBottom,
  fieldHorizontal,
  modalLabel,
  iconContainer,
  icon,
  fullWidth,
  modal,
  textAreaStyle,
  right,
  button,
  buttonRemove,
  buttonAdd,
  addCircleIcon,
  imageText,
  addPeriode,
};

declare const __default_export__: {
  periodeContainer: typeof periodeContainer;
  relative: typeof relative;
  addArbeidsforhold: typeof addArbeidsforhold;
  oppdaterMargin: typeof oppdaterMargin;
  suffix: typeof suffix;
  textAlignRight: typeof textAlignRight;
  alignRightHorizontalBottom: typeof alignRightHorizontalBottom;
  fieldHorizontal: typeof fieldHorizontal;
  modalLabel: typeof modalLabel;
  iconContainer: typeof iconContainer;
  icon: typeof icon;
  fullWidth: typeof fullWidth;
  modal: typeof modal;
  textAreaStyle: typeof textAreaStyle;
  right: typeof right;
  button: typeof button;
  buttonRemove: typeof buttonRemove;
  buttonAdd: typeof buttonAdd;
  addCircleIcon: typeof addCircleIcon;
  imageText: typeof imageText;
  addPeriode: typeof addPeriode;
};
export default __default_export__;
