/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const loader: string;
declare const heading: string;
declare const alert: string;
declare const notater: string;
declare const nyttNotat: string;
declare const visAlleNotater: string;
declare const leggTilNotatKnapp: string;

export {
	loader,
	heading,
	alert,
	notater,
	nyttNotat,
	visAlleNotater,
	leggTilNotatKnapp
};

declare const __default_export__: {
	loader: typeof loader;
	heading: typeof heading;
	alert: typeof alert;
	notater: typeof notater;
	nyttNotat: typeof nyttNotat;
	visAlleNotater: typeof visAlleNotater;
	leggTilNotatKnapp: typeof leggTilNotatKnapp;
};
export default __default_export__;
