/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const loader: string;
declare const heading: string;
declare const alert: string;
declare const notater: string;
declare const nyttNotat: string;
declare const visAlleNotater: string;
declare const leggTilNotatKnapp: string;

export {
	loader,
	heading,
	alert,
	notater,
	nyttNotat,
	visAlleNotater,
	leggTilNotatKnapp
};

declare const __default_export__: {
	loader: typeof loader;
	heading: typeof heading;
	alert: typeof alert;
	notater: typeof notater;
	nyttNotat: typeof nyttNotat;
	visAlleNotater: typeof visAlleNotater;
	leggTilNotatKnapp: typeof leggTilNotatKnapp;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoibm90YXRlci5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbIm5vdGF0ZXIubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBTUE7Y0FNQTtjQUlBO2NBTUE7Y0FJQTtjQUlzQjs7O0NBOUJ0QjtDQU1BO0NBTUE7Q0FJQTtDQU1BO0NBSUE7Q0FJc0I7Ozs7Q0E5QnRCO0NBTUE7Q0FNQTtDQUlBO0NBTUE7Q0FJQTtDQUlzQjs7In0=
