apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-sak-web
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
  annotations:
    nais.io/run-as-user: "101" # Fix permissions for nginx
    nais.io/read-only-file-system: "false" # Fix permissions for nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  image: {{ image }}
  port: 9000
  liveness:
    path: /isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /isReady
    initialDelay: 20
    timeout: 1
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 64Mi
    requests:
      cpu: 200m
      memory: 32Mi
  ingresses:
    - "https://k9.intern.dev.nav.no"
  accessPolicy:
    outbound:
      external:
        - host: "k9-sak.dev-fss-pub.nais.io"
  env:
    - name: APP_NAME
      value: k9-sak-web
    - name: APP_URL
      value: "https://k9-sak.dev-fss-pub.nais.io"
    - name: APP_PORT
      value: "9000"
    - name: APP_URL_K9FORMIDLING
      value: "https://k9-formidling.dev-fss-pub.nais.io"
    - name: APP_URL_K9FORMIDLING_DD
      value: "https://k9-formidling-dokumentdata.dev-fss-pub.nais.io"
    - name: APP_URL_K9OPPDRAG
      value: "https://k9-oppdrag.dev-fss-pub.nais.io"
    - name: APP_URL_KLAGE
      value: "https://k9-klage.dev-fss-pub.nais.io"
    - name: APP_URL_K9TILBAKE
      value: "https://k9-tilbake.dev-fss-pub.nais.io"
    - name: APP_URL_K9FORDEL
      value: "https://k9-fordel.dev-fss-pub.nais.io"
    - name: ENDRINGSLOGG_URL
      value: "https://familie-endringslogg.intern.dev.nav.no/"

    # Feature-flag
    - name: KLAGE_KABAL
      value: "true"
    - name: VARSELTEKST
      value: "true"
    - name: DOKUMENTDATA
      value: "true"
    - name: UNNTAKSBEHANDLING
      value: "true"
    - name: KLAGEBEHANDLING
      value: "true"
    - name: TILBAKE
      value: "true"
    - name: SOKNADPERIODESTRIPE
      value: "false"
    - name: TYPE_MEDISINSKE_OPPLYSNINGER_BREV
      value: "true"
    - name: LOS_MARKER_BEHANDLING
      value: "true"
    - name: LOS_MARKER_BEHANDLING_SUBMIT
      value: "true"
    - name: AKSJONSPUNKT_9014
      value: "true"
    - name: AKSJONSPUNKT_9015
      value: "true"
    - name: FRITEKST_REDIGERING
      value: "true"
    - name: INKLUDER_KALENDER_PILS
      value: "true"
    - name: SKJUL_AVSLUTTET_ARBEIDSGIVER
      value: "true"
    - name: OMS_PUNSJSTRIPE
      value: "true"
    - name: OMSORGEN_FOR_PERIODISERT
      value: "true"
    - name: OVERSTYR_BEREGNING
      value: "true"
    - name: "OVERSTYRING_UTTAK"
      value: "true"
