# Verdier for dev-fss.k9saksbehandling.yml ved utrulling frå dev-next1 branch til k9-next1.dev.intern.nav.no
name: aktivitetspenger-sak-web
ingress: "https://aktivitetspenger.intern.dev.nav.no/"
replicas:
  min: 1
  max: 2
# k9-next1 stoppast etter 10 dager uten ny deploy
ttl: 240h
