apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-sak-web
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
  annotations:
    nais.io/run-as-user: "101" # Fix permissions for nginx
    nais.io/read-only-file-system: "false" # Fix permissions for nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  image: { { image } }
  port: 9000
  team: k9saksbehandling
  liveness:
    path: /isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /isReady
    initialDelay: 20
    timeout: 1
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 64Mi
    requests:
      cpu: 200m
      memory: 32Mi
  ingresses:
    - "https://app.adeo.no/k9"
  env:
    - name: APP_NAME
      value: k9-sak-web
    - name: APP_URL
      value: "http://k9-sak"
    - name: APP_PORT
      value: "9000"
    - name: APP_URL_K9FORMIDLING
      value: "http://k9-formidling"
    - name: APP_URL_K9FORMIDLING_DD
      value: "http://k9-formidling-dokumentdata.k9saksbehandling"
    - name: APP_URL_K9OPPDRAG
      value: "http://k9-oppdrag.default"
    - name: APP_URL_KLAGE
      value: "http://k9-klage.k9saksbehandling"
    - name: APP_URL_K9TILBAKE
      value: "http://k9-tilbake.default"
    - name: APP_URL_K9FORDEL
      value: "http://k9-fordel.k9saksbehandling"
    - name: APP_DIAGNOSEKODER
      value: "http://diagnosekode-api.k9saksbehandling/diagnosekoder"
    - name: MEDISINSK_VILKAR_FRONTEND_URL
      value: "https://medisinsk-vilkar-frontend.intern.nav.no/"
    - name: OMSORGSDAGER_FRONTEND_URL
      value: "https://omsorgsdager-frontend.intern.nav.no/"
    - name: PSB_UTTAK_FRONTEND_URL
      value: "https://psb-uttak-frontend.intern.nav.no/"
    - name: OMSORGEN_FOR_FRONTEND_URL
      value: "https://omsorgen-for-frontend.intern.nav.no/"
    - name: PSB_INNTEKTSMELDING_FRONTEND_URL
      value: "https://psb-inntektsmelding-frontend.intern.nav.no/"
    - name: PSB_ETABLERT_TILSYN_FRONTEND_URL
      value: "https://psb-etablert-tilsyn-frontend.intern.nav.no/"
    - name: PSB_OM_BARNET_FRONTEND_URL
      value: "https://psb-om-barnet-frontend.intern.nav.no/"
    - name: ENDRINGSLOGG_URL
      value: "https://familie-endringslogg.intern.nav.no/"

    # Feature-flag
    - name: KLAGE_KABAL
      value: "true"
    - name: VARSELTEKST
      value: "true"
    - name: DOKUMENTDATA
      value: "false"
    - name: UNNTAKSBEHANDLING
      value: "false"
    - name: KLAGEBEHANDLING
      value: "true"
    - name: TILBAKE
      value: "true"
    - name: UTENLANDSOPPHOLD
      value: "true"
    - name: SOKNADPERIODESTRIPE
      value: "false"
    - name: TYPE_MEDISINSKE_OPPLYSNINGER_BREV
      value: "true"
    - name: LOS_MARKER_BEHANDLING
      value: "true"
    - name: AKSJONSPUNKT_9014
      value: "true"
    - name: AKSJONSPUNKT_9015
      value: "true"
    - name: NY_PROSESS_VEDTAK_ENABLED
      value: "true"
    - name: FRITEKST_REDIGERING
      value: "true"
    - name: INKLUDER_KALENDER_PILS
      value: "false"
    - name: OPPLAERINGSPENGER
      value: "false"
