/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const alertModalInnehold: string;
declare const knapper: string;
declare const hoyere: string;
declare const knapperHoyere: string;
declare const nullstillCss: string;
declare const papir: string;
declare const ikkeRedigerbartInnhold: string;
declare const redigerbartInnhold: string;
declare const alertMeldinger: string;
declare const skjulEditor: string;

export {
	alertModalInnehold,
	knapper,
	hoyere,
	knapperHoyere,
	nullstillCss,
	papir,
	ikkeRedigerbartInnhold,
	redigerbartInnhold,
	alertMeldinger,
	skjulEditor
};

declare const __default_export__: {
	alertModalInnehold: typeof alertModalInnehold;
	knapper: typeof knapper;
	hoyere: typeof hoyere;
	knapperHoyere: typeof knapperHoyere;
	nullstillCss: typeof nullstillCss;
	papir: typeof papir;
	ikkeRedigerbartInnhold: typeof ikkeRedigerbartInnhold;
	redigerbartInnhold: typeof redigerbartInnhold;
	alertMeldinger: typeof alertMeldinger;
	skjulEditor: typeof skjulEditor;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiUmVkaWdlckZyaXRla3N0YnJldi5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbIlJlZGlnZXJGcml0ZWtzdGJyZXYubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUVBO2NBSUE7Y0FnQkE7Y0FJQTtjQVNBO2NBSUE7Y0FVQTtjQUtBO2NBUUE7Y0FRQTs7O0NBcEVBO0NBSUE7Q0FnQkE7Q0FJQTtDQVNBO0NBSUE7Q0FVQTtDQUtBO0NBUUE7Q0FRQTs7OztDQXBFQTtDQUlBO0NBZ0JBO0NBSUE7Q0FTQTtDQUlBO0NBVUE7Q0FLQTtDQVFBO0NBUUE7OyJ9
