/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const alertModalInnehold: string;
declare const knapper: string;
declare const hoyere: string;
declare const knapperHoyere: string;
declare const nullstillCss: string;
declare const papir: string;
declare const ikkeRedigerbartInnhold: string;
declare const redigerbartInnhold: string;
declare const alertMeldinger: string;
declare const skjulEditor: string;

export {
  alertModalInnehold,
  knapper,
  hoyere,
  knapperHoyere,
  nullstillCss,
  papir,
  ikkeRedigerbartInnhold,
  redigerbartInnhold,
  alertMeldinger,
  skjulEditor,
};

declare const __default_export__: {
  alertModalInnehold: typeof alertModalInnehold;
  knapper: typeof knapper;
  hoyere: typeof hoyere;
  knapperHoyere: typeof knapperHoyere;
  nullstillCss: typeof nullstillCss;
  papir: typeof papir;
  ikkeRedigerbartInnhold: typeof ikkeRedigerbartInnhold;
  redigerbartInnhold: typeof redigerbartInnhold;
  alertMeldinger: typeof alertMeldinger;
  skjulEditor: typeof skjulEditor;
};
export default __default_export__;
