/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const interactiveList: string;
declare const interactiveListElement: string;
declare const interactiveListElementInactive: string;
declare const interactiveListElementActive: string;

export {
	interactiveList,
	interactiveListElement,
	interactiveListElementInactive,
	interactiveListElementActive
};

declare const __default_export__: {
	interactiveList: typeof interactiveList;
	interactiveListElement: typeof interactiveListElement;
	interactiveListElementInactive: typeof interactiveListElementInactive;
	interactiveListElementActive: typeof interactiveListElementActive;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicGVyaW9kZVJhZC5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbInBlcmlvZGVSYWQubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBTUE7Y0FvQkE7Y0FJQTs7O0NBOUJBO0NBTUE7Q0FvQkE7Q0FJQTs7OztDQTlCQTtDQU1BO0NBb0JBO0NBSUE7OyJ9
