/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const contentContainer: string;
declare const sideMenuContainer: string;
declare const mainContainerWithSideMenu: string;
declare const vilkar: string;
declare const statusMelding: string;

export {
	contentContainer,
	sideMenuContainer,
	mainContainerWithSideMenu,
	vilkar,
	statusMelding
};

declare const __default_export__: {
	contentContainer: typeof contentContainer;
	sideMenuContainer: typeof sideMenuContainer;
	mainContainerWithSideMenu: typeof mainContainerWithSideMenu;
	vilkar: typeof vilkar;
	statusMelding: typeof statusMelding;
};
export default __default_export__;
