/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const harSidemeny: string;
declare const vilkar: string;

export {
	harSidemeny,
	vilkar
};

declare const __default_export__: {
	harSidemeny: typeof harSidemeny;
	vilkar: typeof vilkar;
};
export default __default_export__;
