/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const modal: string;

export { modal };

declare const __default_export__: {
  modal: typeof modal;
};
export default __default_export__;
