/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const personIcon: string;

export { personIcon };

declare const __default_export__: {
  personIcon: typeof personIcon;
};
export default __default_export__;
