/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const lastRow: string;
declare const firstHeaderCell: string;

export { lastRow, firstHeaderCell };

declare const __default_export__: {
  lastRow: typeof lastRow;
  firstHeaderCell: typeof firstHeaderCell;
};
export default __default_export__;
