/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const expanded: string;
declare const uttakExpandButton: string;
declare const uttakExpandButtonExpanded: string;
declare const uttakIndikator: string;
declare const uttakIndikatorAvsl_tt: string;
declare const uttakIndikatorInnvilget: string;
declare const uttakIndikatorInnvilgetDelvis: string;
declare const uttakIndikatorInnvilgetDelvisInntekt: string;
declare const uttakUttaksgrad: string;
declare const uttakUttaksgradTekst: string;
declare const uttakIconContainer: string;
declare const uttakIconWide: string;
declare const uttakExpandedRow: string;
declare const uttakBehandlerIcon: string;
declare const uttakLastColumn: string;
declare const borderLeft: string;
declare const borderRight: string;
declare const borderTop: string;
declare const collapseRow: string;
declare const expandedRow: string;
declare const uttakVilkarIconContainer: string;

export {
  expanded,
  uttakExpandButton,
  uttakExpandButtonExpanded,
  uttakIndikator,
  uttakIndikatorInnvilget,
  uttakIndikatorInnvilgetDelvis,
  uttakIndikatorInnvilgetDelvisInntekt,
  uttakUttaksgrad,
  uttakUttaksgradTekst,
  uttakIconContainer,
  uttakIconWide,
  uttakExpandedRow,
  uttakBehandlerIcon,
  uttakLastColumn,
  borderLeft,
  borderRight,
  borderTop,
  collapseRow,
  expandedRow,
  uttakVilkarIconContainer,
};

declare const __default_export__: {
  expanded: typeof expanded;
  uttakExpandButton: typeof uttakExpandButton;
  uttakExpandButtonExpanded: typeof uttakExpandButtonExpanded;
  uttakIndikator: typeof uttakIndikator;
  uttakIndikatorAvslått: typeof uttakIndikatorAvsl_tt;
  uttakIndikatorInnvilget: typeof uttakIndikatorInnvilget;
  uttakIndikatorInnvilgetDelvis: typeof uttakIndikatorInnvilgetDelvis;
  uttakIndikatorInnvilgetDelvisInntekt: typeof uttakIndikatorInnvilgetDelvisInntekt;
  uttakUttaksgrad: typeof uttakUttaksgrad;
  uttakUttaksgradTekst: typeof uttakUttaksgradTekst;
  uttakIconContainer: typeof uttakIconContainer;
  uttakIconWide: typeof uttakIconWide;
  uttakExpandedRow: typeof uttakExpandedRow;
  uttakBehandlerIcon: typeof uttakBehandlerIcon;
  uttakLastColumn: typeof uttakLastColumn;
  borderLeft: typeof borderLeft;
  borderRight: typeof borderRight;
  borderTop: typeof borderTop;
  collapseRow: typeof collapseRow;
  expandedRow: typeof expandedRow;
  uttakVilkarIconContainer: typeof uttakVilkarIconContainer;
};
export default __default_export__;
