/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const headerColumn: string;
declare const alertRow: string;
declare const redigerDato: string;
declare const oppholdRow: string;
declare const tableContainer: string;

export {
	headerColumn,
	alertRow,
	redigerDato,
	oppholdRow,
	tableContainer
};

declare const __default_export__: {
	headerColumn: typeof headerColumn;
	alertRow: typeof alertRow;
	redigerDato: typeof redigerDato;
	oppholdRow: typeof oppholdRow;
	tableContainer: typeof tableContainer;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidXR0YWtzcGVyaW9kZUxpc3RlLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsidXR0YWtzcGVyaW9kZUxpc3RlLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQU9BO2NBWUE7Y0FLQTtjQVNFOzs7Q0FqQ0Y7Q0FPQTtDQVlBO0NBS0E7Q0FTRTs7OztDQWpDRjtDQU9BO0NBWUE7Q0FLQTtDQVNFOzsifQ==
