/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const vilk_rsliste: string;
declare const item: string;
declare const itemText: string;

declare const __default_export__: {
	"vilkårsliste": typeof vilk_rsliste;
	item: typeof item;
	itemText: typeof itemText;
};
export default __default_export__;
