/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const vilk_rsliste: string;

declare const __default_export__: {
	"vilkårsliste": typeof vilk_rsliste;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidmlsa8OlcnNsaXN0ZS5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbInZpbGvDpXJzbGlzdGUubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBOzs7OzsifQ==
