/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const item: string;
declare const itemText: string;

export { item, itemText };

declare const __default_export__: {
  item: typeof item;
  itemText: typeof itemText;
};
export default __default_export__;
