/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const item: string;
declare const itemText: string;

export {
	item,
	itemText
};

declare const __default_export__: {
	item: typeof item;
	itemText: typeof itemText;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidmlsa8OlcnNsaXN0ZUl0ZW0ubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJ2aWxrw6Vyc2xpc3RlSXRlbS5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FNQTs7O0NBTkE7Q0FNQTs7OztDQU5BO0NBTUE7OyJ9
