const dokumentdatatype = {
  FRITEKST: 'FRITEKST',
  BEREGNING_FRITEKST: 'BEREGNINGSGRUNNLAG_FRITEKST',
  REDUSERT_UTBETALING_AARSAK: 'REDUSERT_UTBETALING_AARSAK',
  AVSLAG_AARSAK: 'AVSLAG_AARSAK',
  VEDTAKSBREV_TYPE: 'VEDTAKSBREV_TYPE',
};

export default dokumentdatatype;
