const dokumentdatatype = {
  FRITEKSTBREV: 'FRITEKSTBREV',
  BEREGNING_FRITEKST: 'BEREGNINGSGRUNNLAG_FRITEKST',
  REDUSERT_UTBETALING_AARSAK: 'REDUSERT_UTBETALING_AARSAK',
  AVSLAG_AARSAK: 'AVSLAG_AARSAK',
  VEDTAKSBREV_TYPE: 'VEDTAKSBREV_TYPE',
  VEDTAKSBREV_MAL: 'VEDTAKSBREV_MAL',
  OVERSTYRT_MOTTAKER: 'OVERSTYRT_MOTTAKER',
  REDIGERTBREV: 'REDIGERTBREV',
};

export default dokumentdatatype;
