// Definerer koder for alle fakta-penelene.
const faktaPanelCodes = {
  ADOPSJONSVILKARET: 'adopsjonsvilkaaret',
  ARBEIDSFORHOLD: 'arbeidsforhold',
  BEREGNING: 'beregning',
  OVERSTYRING: 'overstyring',
  INFOTRYGDMIGRERING: 'infotrygdmigrering',
  DEFAULT: 'default',
  FORDELING: 'fordeling',
  FEILUTBETALING: 'feilutbetaling',
  FODSELSVILKARET: 'foedselsvilkaaret',
  INNTEKTSMELDING: 'inntektsmelding',
  MEDLEMSKAPSVILKARET: 'medlemskapsvilkaaret',
  MEDISINSKVILKAAR: 'medisinskvilkaar',
  MEDISINSKVILKAAR_V2: 'medisinskvilkaar-v2',
  OMSORG: 'omsorg',
  OMSORGEN_FOR: 'omsorgenfor', // FIXME: oppdater navn når det er landet
  OMSORGSVILKARET: 'omsorgsvilkaaret',
  OPPTJENINGSVILKARET: 'opptjeningsvilkaaret',
  SAKEN: 'saken',
  TILLEGGSOPPLYSNINGER: 'tilleggsopplysninger',
  UTTAK: 'uttak',
  NØKKELTALL: 'nokkeltall',
  BARN: 'barn',
  VERGE: 'verge',
  YTELSER: 'ytelser',
  INNTEKT_OG_YTELSER: 'inntekt-og-ytelser',
  OPPLYSNINGER_FRA_SØKNADEN: 'opplysninger-fra-soknaden',
  ETABLERT_TILSYN: 'etablert-tilsyn',
  OM_BARNET: 'om-barnet',
  OM_PLEIETRENGENDE: 'om-pleietrengende',
  UTENLANDSOPPHOLD: 'utenlandsopphold',
  SOKNADSPERIODER: 'soknadsperioder',
  INSTITUSJON: 'institusjon',
  OPPLAERING: 'opplaering',
};

export default faktaPanelCodes;
