/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const lesemodusboks: string;
declare const text: string;
declare const label: string;
declare const fritekst: string;
declare const aksjonspunktOgRedigerVurderingContainer: string;
declare const redigerVurderingTekst: string;
declare const opplysningerFraSoknad: string;
declare const begrunnelseContainer: string;
declare const alder: string;
declare const barnTekst: string;

export {
	lesemodusboks,
	text,
	label,
	fritekst,
	aksjonspunktOgRedigerVurderingContainer,
	redigerVurderingTekst,
	opplysningerFraSoknad,
	begrunnelseContainer,
	alder,
	barnTekst
};

declare const __default_export__: {
	lesemodusboks: typeof lesemodusboks;
	text: typeof text;
	label: typeof label;
	fritekst: typeof fritekst;
	aksjonspunktOgRedigerVurderingContainer: typeof aksjonspunktOgRedigerVurderingContainer;
	redigerVurderingTekst: typeof redigerVurderingTekst;
	opplysningerFraSoknad: typeof opplysningerFraSoknad;
	begrunnelseContainer: typeof begrunnelseContainer;
	alder: typeof alder;
	barnTekst: typeof barnTekst;
};
export default __default_export__;
