/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const vilkarStatusOverskrift: string;
declare const aksjonspunktNavn: string;
declare const vilkar: string;
declare const vilkarStatus: string;
declare const begrunnelseOverskrift: string;
declare const fritekst: string;
declare const begrunnelse: string;

export {
	vilkarStatusOverskrift,
	aksjonspunktNavn,
	vilkar,
	vilkarStatus,
	begrunnelseOverskrift,
	fritekst,
	begrunnelse
};

declare const __default_export__: {
	vilkarStatusOverskrift: typeof vilkarStatusOverskrift;
	aksjonspunktNavn: typeof aksjonspunktNavn;
	vilkar: typeof vilkar;
	vilkarStatus: typeof vilkarStatus;
	begrunnelseOverskrift: typeof begrunnelseOverskrift;
	fritekst: typeof fritekst;
	begrunnelse: typeof begrunnelse;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQWxkZXJzdmlsa2FyU3RhdHVzLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsiQWxkZXJzdmlsa2FyU3RhdHVzLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQWlCQTtjQUtBO2NBSUE7Y0FNQTtjQU9BO2NBUUE7OztDQS9DQTtDQWlCQTtDQUtBO0NBSUE7Q0FNQTtDQU9BO0NBUUE7Ozs7Q0EvQ0E7Q0FpQkE7Q0FLQTtDQUlBO0NBTUE7Q0FPQTtDQVFBOzsifQ==
