/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const opplysninger: string;
declare const label: string;
declare const barn: string;
declare const vurdering: string;

export { opplysninger, label, barn, vurdering };

declare const __default_export__: {
  opplysninger: typeof opplysninger;
  label: typeof label;
  barn: typeof barn;
  vurdering: typeof vurdering;
};
export default __default_export__;
