/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const lesemodusboks: string;
declare const text: string;
declare const label: string;
declare const fritekst: string;
declare const aksjonspunktOgRedigerVurderingContainer: string;
declare const redigerVurderingTekst: string;
declare const opplysningerFraSoknad: string;
declare const begrunnelseContainer: string;
declare const alder: string;
declare const barnTekst: string;

export {
	lesemodusboks,
	text,
	label,
	fritekst,
	aksjonspunktOgRedigerVurderingContainer,
	redigerVurderingTekst,
	opplysningerFraSoknad,
	begrunnelseContainer,
	alder,
	barnTekst
};

declare const __default_export__: {
	lesemodusboks: typeof lesemodusboks;
	text: typeof text;
	label: typeof label;
	fritekst: typeof fritekst;
	aksjonspunktOgRedigerVurderingContainer: typeof aksjonspunktOgRedigerVurderingContainer;
	redigerVurderingTekst: typeof redigerVurderingTekst;
	opplysningerFraSoknad: typeof opplysningerFraSoknad;
	begrunnelseContainer: typeof begrunnelseContainer;
	alder: typeof alder;
	barnTekst: typeof barnTekst;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQWxkZXJzdmlsa2FyTGVzZS5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbIkFsZGVyc3ZpbGthckxlc2UubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBUUE7Y0FJQTtjQUtBO2NBUUE7Y0FXQTtjQWtCQTtjQWdCQTtjQUlBO2NBV087OztDQXJGUDtDQVFBO0NBSUE7Q0FLQTtDQVFBO0NBV0E7Q0FrQkE7Q0FnQkE7Q0FJQTtDQVdPOzs7O0NBckZQO0NBUUE7Q0FJQTtDQUtBO0NBUUE7Q0FXQTtDQWtCQTtDQWdCQTtDQUlBO0NBV087OyJ9
