/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const vilkarStatusOverskrift: string;
declare const aksjonspunktNavn: string;
declare const vilkar: string;
declare const vilkarStatus: string;
declare const begrunnelseOverskrift: string;
declare const fritekst: string;
declare const begrunnelse: string;

export {
	vilkarStatusOverskrift,
	aksjonspunktNavn,
	vilkar,
	vilkarStatus,
	begrunnelseOverskrift,
	fritekst,
	begrunnelse
};

declare const __default_export__: {
	vilkarStatusOverskrift: typeof vilkarStatusOverskrift;
	aksjonspunktNavn: typeof aksjonspunktNavn;
	vilkar: typeof vilkar;
	vilkarStatus: typeof vilkarStatus;
	begrunnelseOverskrift: typeof begrunnelseOverskrift;
	fritekst: typeof fritekst;
	begrunnelse: typeof begrunnelse;
};
export default __default_export__;
