/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const opplysninger: string;
declare const label: string;
declare const barn: string;
declare const vurdering: string;

export {
	opplysninger,
	label,
	barn,
	vurdering
};

declare const __default_export__: {
	opplysninger: typeof opplysninger;
	label: typeof label;
	barn: typeof barn;
	vurdering: typeof vurdering;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQWxkZXJzdmlsa2FyRm9ybS5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbIkFsZGVyc3ZpbGthckZvcm0ubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBTWM7Y0FJZDtjQUlBOzs7Q0FkQTtDQU1jO0NBSWQ7Q0FJQTs7OztDQWRBO0NBTWM7Q0FJZDtDQUlBOzsifQ==
