/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const brevCheckboxContainer: string;

export {
	brevCheckboxContainer
};

declare const __default_export__: {
	brevCheckboxContainer: typeof brevCheckboxContainer;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidW5nVmVkdGFrLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsidW5nVmVkdGFrLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTs7O0NBQUE7Ozs7Q0FBQTs7In0=
