/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const brevCheckboxContainer: string;

export {
	brevCheckboxContainer
};

declare const __default_export__: {
	brevCheckboxContainer: typeof brevCheckboxContainer;
};
export default __default_export__;
