/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const uttakDetaljer: string;
declare const uttakDetaljerGraderingDetaljer: string;
declare const uttakDetaljerGraderingDetaljerHighlighted: string;
declare const uttakDetaljerGraderingDetaljerNotHighlighted: string;
declare const uttakDetaljerDetailItem: string;
declare const uttakDetaljerDetailSum: string;
declare const uttakDetaljerDataQuestionMark: string;
declare const uttakDetaljerExpandableDetailItem: string;
declare const uttakDetaljerExpandableDetailItemHeader: string;
declare const uttakDetaljerExpandableDetailItemContentCollapsed: string;
declare const uttakDetaljerNyGradering: string;
declare const uttakDetaljerTag: string;
declare const uttakDetaljerBeregningFirma: string;
declare const uttakDetaljerTaptInntektBeregning: string;
declare const uttakDetaljerTaptInntektAnnotasjon: string;
declare const uttakDetaljerBeregningStrek: string;
declare const uttakDetaljerBeregningSum: string;
declare const uttakDetaljerUtnullet: string;
declare const uttakDetaljerNyTag: string;
declare const uttakDetaljerDetailtext: string;

export {
	uttakDetaljer,
	uttakDetaljerGraderingDetaljer,
	uttakDetaljerGraderingDetaljerHighlighted,
	uttakDetaljerGraderingDetaljerNotHighlighted,
	uttakDetaljerDetailItem,
	uttakDetaljerDetailSum,
	uttakDetaljerDataQuestionMark,
	uttakDetaljerExpandableDetailItem,
	uttakDetaljerExpandableDetailItemHeader,
	uttakDetaljerExpandableDetailItemContentCollapsed,
	uttakDetaljerNyGradering,
	uttakDetaljerTag,
	uttakDetaljerBeregningFirma,
	uttakDetaljerTaptInntektBeregning,
	uttakDetaljerTaptInntektAnnotasjon,
	uttakDetaljerBeregningStrek,
	uttakDetaljerBeregningSum,
	uttakDetaljerUtnullet,
	uttakDetaljerNyTag,
	uttakDetaljerDetailtext
};

declare const __default_export__: {
	uttakDetaljer: typeof uttakDetaljer;
	uttakDetaljerGraderingDetaljer: typeof uttakDetaljerGraderingDetaljer;
	uttakDetaljerGraderingDetaljerHighlighted: typeof uttakDetaljerGraderingDetaljerHighlighted;
	uttakDetaljerGraderingDetaljerNotHighlighted: typeof uttakDetaljerGraderingDetaljerNotHighlighted;
	uttakDetaljerDetailItem: typeof uttakDetaljerDetailItem;
	uttakDetaljerDetailSum: typeof uttakDetaljerDetailSum;
	uttakDetaljerDataQuestionMark: typeof uttakDetaljerDataQuestionMark;
	uttakDetaljerExpandableDetailItem: typeof uttakDetaljerExpandableDetailItem;
	uttakDetaljerExpandableDetailItemHeader: typeof uttakDetaljerExpandableDetailItemHeader;
	uttakDetaljerExpandableDetailItemContentCollapsed: typeof uttakDetaljerExpandableDetailItemContentCollapsed;
	uttakDetaljerNyGradering: typeof uttakDetaljerNyGradering;
	uttakDetaljerTag: typeof uttakDetaljerTag;
	uttakDetaljerBeregningFirma: typeof uttakDetaljerBeregningFirma;
	uttakDetaljerTaptInntektBeregning: typeof uttakDetaljerTaptInntektBeregning;
	uttakDetaljerTaptInntektAnnotasjon: typeof uttakDetaljerTaptInntektAnnotasjon;
	uttakDetaljerBeregningStrek: typeof uttakDetaljerBeregningStrek;
	uttakDetaljerBeregningSum: typeof uttakDetaljerBeregningSum;
	uttakDetaljerUtnullet: typeof uttakDetaljerUtnullet;
	uttakDetaljerNyTag: typeof uttakDetaljerNyTag;
	uttakDetaljerDetailtext: typeof uttakDetaljerDetailtext;
};
export default __default_export__;
