/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const uttakUtregning: string;
declare const uttakUtregningHighlighted: string;
declare const uttakUtregningHeadingContainer: string;
declare const uttakUtregningHeadingIcon: string;

export {
	uttakUtregning,
	uttakUtregningHighlighted,
	uttakUtregningHeadingContainer,
	uttakUtregningHeadingIcon
};

declare const __default_export__: {
	uttakUtregning: typeof uttakUtregning;
	uttakUtregningHighlighted: typeof uttakUtregningHighlighted;
	uttakUtregningHeadingContainer: typeof uttakUtregningHeadingContainer;
	uttakUtregningHeadingIcon: typeof uttakUtregningHeadingIcon;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidXR0YWtVdHJlZ25pbmcubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJ1dHRha1V0cmVnbmluZy5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FNQTtjQU1BO2NBSUE7OztDQWhCQTtDQU1BO0NBTUE7Q0FJQTs7OztDQWhCQTtDQU1BO0NBTUE7Q0FJQTs7In0=
