/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const divider: string;
declare const image: string;
declare const modal: string;
declare const label: string;
declare const right: string;
declare const datePickerContainer: string;

export {
	container,
	divider,
	image,
	modal,
	label,
	right,
	datePickerContainer
};

declare const __default_export__: {
	container: typeof container;
	divider: typeof divider;
	image: typeof image;
	modal: typeof modal;
	label: typeof label;
	right: typeof right;
	datePickerContainer: typeof datePickerContainer;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoibnlCZWhhbmRsaW5nTW9kYWwubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJueUJlaGFuZGxpbmdNb2RhbC5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FJQTtjQVdBO2NBTUE7Y0FJQTtjQUlBO2NBS0E7OztDQWxDQTtDQUlBO0NBV0E7Q0FNQTtDQUlBO0NBSUE7Q0FLQTs7OztDQWxDQTtDQUlBO0NBV0E7Q0FNQTtDQUlBO0NBSUE7Q0FLQTs7In0=
