/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const divider: string;
declare const image: string;
declare const modal: string;
declare const label: string;
declare const right: string;
declare const datePickerContainer: string;

export { container, divider, image, modal, label, right, datePickerContainer };

declare const __default_export__: {
  container: typeof container;
  divider: typeof divider;
  image: typeof image;
  modal: typeof modal;
  label: typeof label;
  right: typeof right;
  datePickerContainer: typeof datePickerContainer;
};
export default __default_export__;
