/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const sectionHeadingRow: string;
declare const infoCard: string;
declare const expandedCard: string;
declare const expandedRows: string;
declare const expandedRow: string;
declare const expandedLabel: string;
declare const sistEndret: string;

export {
	container,
	sectionHeadingRow,
	infoCard,
	expandedCard,
	expandedRows,
	expandedRow,
	expandedLabel,
	sistEndret
};

declare const __default_export__: {
	container: typeof container;
	sectionHeadingRow: typeof sectionHeadingRow;
	infoCard: typeof infoCard;
	expandedCard: typeof expandedCard;
	expandedRows: typeof expandedRows;
	expandedRow: typeof expandedRow;
	expandedLabel: typeof expandedLabel;
	sistEndret: typeof sistEndret;
};
export default __default_export__;
