/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const infostripe: string;
declare const iconContainer: string;

export {
	infostripe,
	iconContainer
};

declare const __default_export__: {
	infostripe: typeof infostripe;
	iconContainer: typeof iconContainer;
};
export default __default_export__;
