/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const infostripe: string;
declare const iconContainer: string;

export {
	infostripe,
	iconContainer
};

declare const __default_export__: {
	infostripe: typeof infostripe;
	iconContainer: typeof iconContainer;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5mb3N0cmlwZS5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbImluZm9zdHJpcGUubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBU0E7OztDQVRBO0NBU0E7Ozs7Q0FUQTtDQVNBOzsifQ==
