enum Vurderingsresultat {
  MÅ_VURDERES = 'MÅ_VURDERES',
  GODKJENT = 'GODKJENT',
  IKKE_GODKJENT = 'IKKE_GODKJENT',
  GODKJENT_MANUELT = 'GODKJENT_MANUELT',
  GODKJENT_AUTOMATISK = 'GODKJENT_AUTOMATISK',
  IKKE_GODKJENT_MANUELT = 'IKKE_GODKJENT_MANUELT',
  IKKE_GODKJENT_AUTOMATISK = 'IKKE_GODKJENT_AUTOMATISK',
}

export default Vurderingsresultat;
