enum Vurderingsresultat {
  OPPFYLT = 'OPPFYLT',
  IKKE_OPPFYLT = 'IKKE_OPPFYLT',
  IKKE_VURDERT = 'IKKE_VURDERT',
  OPPFYLT_AUTOMATISK = 'OPPFYLT_AUTOMATISK',
  IKKE_OPPFYLLT_AUTOMATISK = 'IKKE_OPPFYLLT_AUTOMATISK',
}

export default Vurderingsresultat;
