/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const lovreferanse: string;

export { lovreferanse };

declare const __default_export__: {
  lovreferanse: typeof lovreferanse;
};
export default __default_export__;
