/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const lovreferanse: string;

export {
	lovreferanse
};

declare const __default_export__: {
	lovreferanse: typeof lovreferanse;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidW5nSW5uZ2FuZ3N2aWxrw6VyLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsidW5nSW5uZ2FuZ3N2aWxrw6VyLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTs7O0NBQUE7Ozs7Q0FBQTs7In0=
