/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const mainContainerWithSideMenu: string;
declare const warningIcon: string;

export {
	mainContainerWithSideMenu,
	warningIcon
};

declare const __default_export__: {
	mainContainerWithSideMenu: typeof mainContainerWithSideMenu;
	warningIcon: typeof warningIcon;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoib3BwdGplbmluZ1ZpbGthclByb3Nlc3NJbmRleC5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbIm9wcHRqZW5pbmdWaWxrYXJQcm9zZXNzSW5kZXgubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBS0E7OztDQUxBO0NBS0E7Ozs7Q0FMQTtDQUtBOzsifQ==
