export const klageVurderingType = {
  STADFESTE_YTELSESVEDTAK: 'STADFESTE_YTELSESVEDTAK',
  MEDHOLD_I_KLAGE: 'MEDHOLD_I_KLAGE',
  OPPHEVE_YTELSESVEDTAK: 'OPPHEVE_YTELSESVEDTAK',
  AVVIS_KLAGE: 'AVVIS_KLAGE',
  HJEMSENDE_UTEN_Å_OPPHEVE: 'HJEMSENDE_UTEN_Å_OPPHEVE',
  TRUKKET_KLAGE: 'TRUKKET_KLAGE',
  FEILREGISTRERT: 'FEILREGISTRERT',
};

export const klageVurderingOmgjoerType = {
  DELVIS_MEDHOLD_I_KLAGE: 'DELVIS_MEDHOLD_I_KLAGE',
  GUNST_MEDHOLD_I_KLAGE: 'GUNST_MEDHOLD_I_KLAGE',
  UGUNST_MEDHOLD_I_KLAGE: 'UGUNST_MEDHOLD_I_KLAGE',
  UDEFINERT: '-',
};
