/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const visItem: string;
declare const visDot: string;
declare const visSelected: string;
declare const visTimeline: string;
declare const timelineContainer: string;
declare const fadein: string;
declare const timelineContainerExpanded: string;
declare const open: string;
declare const iconContainer: string;
declare const image: string;
declare const sokerContainer: string;
declare const showDataPanel: string;
declare const hiddenpast: string;
declare const detailsPeriode: string;
declare const tilkjentYtelseTag: string;
declare const showDataContainer: string;
declare const fadeinContainer: string;

export {
  timelineContainer,
  fadein,
  timelineContainerExpanded,
  open,
  iconContainer,
  image,
  sokerContainer,
  showDataPanel,
  hiddenpast,
  detailsPeriode,
  tilkjentYtelseTag,
  showDataContainer,
  fadeinContainer,
};

declare const __default_export__: {
  'vis-item': typeof visItem;
  'vis-dot': typeof visDot;
  'vis-selected': typeof visSelected;
  'vis-timeline': typeof visTimeline;
  timelineContainer: typeof timelineContainer;
  fadein: typeof fadein;
  timelineContainerExpanded: typeof timelineContainerExpanded;
  open: typeof open;
  iconContainer: typeof iconContainer;
  image: typeof image;
  sokerContainer: typeof sokerContainer;
  showDataPanel: typeof showDataPanel;
  hiddenpast: typeof hiddenpast;
  detailsPeriode: typeof detailsPeriode;
  tilkjentYtelseTag: typeof tilkjentYtelseTag;
  showDataContainer: typeof showDataContainer;
  fadeinContainer: typeof fadeinContainer;
};
export default __default_export__;
