/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const infostripe: string;
declare const infostripePunktliste: string;

export {
	infostripe,
	infostripePunktliste
};

declare const __default_export__: {
	infostripe: typeof infostripe;
	infostripePunktliste: typeof infostripePunktliste;
};
export default __default_export__;
