/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const infostripe: string;
declare const infostripePunktliste: string;

export {
	infostripe,
	infostripePunktliste
};

declare const __default_export__: {
	infostripe: typeof infostripe;
	infostripePunktliste: typeof infostripePunktliste;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5mb3N0cmlwZS5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbImluZm9zdHJpcGUubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBS0E7OztDQUxBO0NBS0E7Ozs7Q0FMQTtDQUtBOzsifQ==
