/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const confirmVilkarForm: string;

export {
	confirmVilkarForm
};

declare const __default_export__: {
	confirmVilkarForm: typeof confirmVilkarForm;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYmVoYW5kbGVLbGFnZUZvcm1LYS5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbImJlaGFuZGxlS2xhZ2VGb3JtS2EubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBOzs7Q0FBQTs7OztDQUFBOzsifQ==
