/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const selectReadOnly: string;

export {
	selectReadOnly
};

declare const __default_export__: {
	selectReadOnly: typeof selectReadOnly;
};
export default __default_export__;
