/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const selectReadOnly: string;

export {
	selectReadOnly
};

declare const __default_export__: {
	selectReadOnly: typeof selectReadOnly;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoia2xhZ2VWdXJkZXJpbmdSYWRpb09wdGlvbnNLYS5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbImtsYWdlVnVyZGVyaW5nUmFkaW9PcHRpb25zS2EubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBOzs7Q0FBQTs7OztDQUFBOzsifQ==
