export enum OverstyrUttakFormFieldName {
  FOM = 'fom',
  TOM = 'tom',
  UTTAKSGRAD = 'søkersUttaksgrad',
  OVERSTYRING = 'overstyring',
  BEGRUNNELSE = 'begrunnelse',
  UTBETALINGSGRADER = 'utbetalingsgrader',
  UTBETALINGSGRAD = 'utbetalingsgrad',
  AKTIVITET_ID = 'aktivitetId',
  AKTIVITET_NAVN = 'aktivitetNavn',
  AKTIVITET_UTBETALINGSGRAD = 'aktivitetUtbetalingsgrad',
  ARBEIDSFORHOLD = 'arbeidsforhold',
  TYPE = 'type',
  ORGANISASJONSNUMMER = 'organisasjonsnummer',
  AKTØR_ID = 'aktørId',
  ARBEIDSFORHOLD_ID = 'arbeidsforholdId',
}
