/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const vilk_rsliste: string;

declare const __default_export__: {
	"vilkårsliste": typeof vilk_rsliste;
};
export default __default_export__;
