/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const titelOgHjelpetekstFlexbox: string;

export { titelOgHjelpetekstFlexbox };

declare const __default_export__: {
  titelOgHjelpetekstFlexbox: typeof titelOgHjelpetekstFlexbox;
};
export default __default_export__;
