/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const vilkar: string;
declare const status: string;

export {
	vilkar,
	status
};

declare const __default_export__: {
	vilkar: typeof vilkar;
	status: typeof status;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoib3BwdGplbmluZ1BhbmVsLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsib3BwdGplbmluZ1BhbmVsLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQUlBOzs7Q0FKQTtDQUlBOzs7O0NBSkE7Q0FJQTs7In0=
