/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const titelOgHjelpetekstFlexbox: string;

export {
	titelOgHjelpetekstFlexbox
};

declare const __default_export__: {
	titelOgHjelpetekstFlexbox: typeof titelOgHjelpetekstFlexbox;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiT3BwdGplbmluZ1ZpbGthckFrc2pvbnNwdW5rdFBhbmVsLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsiT3BwdGplbmluZ1ZpbGthckFrc2pvbnNwdW5rdFBhbmVsLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTs7O0NBQUE7Ozs7Q0FBQTs7In0=
