/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const vilkar: string;
declare const status: string;

export {
	vilkar,
	status
};

declare const __default_export__: {
	vilkar: typeof vilkar;
	status: typeof status;
};
export default __default_export__;
