/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const image: string;

export {
	image
};

declare const __default_export__: {
	image: typeof image;
};
export default __default_export__;
