/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const modal: string;
declare const infotekstBeskrivelse: string;
declare const image: string;
declare const divider: string;
declare const floatButtons: string;

export {
	modal,
	infotekstBeskrivelse,
	image,
	divider,
	floatButtons
};

declare const __default_export__: {
	modal: typeof modal;
	infotekstBeskrivelse: typeof infotekstBeskrivelse;
	image: typeof image;
	divider: typeof divider;
	floatButtons: typeof floatButtons;
};
export default __default_export__;
