/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const modal: string;
declare const infotekstBeskrivelse: string;
declare const image: string;
declare const divider: string;
declare const floatButtons: string;

export {
	modal,
	infotekstBeskrivelse,
	image,
	divider,
	floatButtons
};

declare const __default_export__: {
	modal: typeof modal;
	infotekstBeskrivelse: typeof infotekstBeskrivelse;
	image: typeof image;
	divider: typeof divider;
	floatButtons: typeof floatButtons;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZW5kcmVCZWhhbmRsZW5kZUVuaGV0TW9kYWwubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJlbmRyZUJlaGFuZGxlbmRlRW5oZXRNb2RhbC5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FJQTtjQUlBO2NBTUE7Y0FXQTs7O0NBekJBO0NBSUE7Q0FJQTtDQU1BO0NBV0E7Ozs7Q0F6QkE7Q0FJQTtDQUlBO0NBTUE7Q0FXQTs7In0=
