enum Vurderingstype {
  KONTINUERLIG_TILSYN_OG_PLEIE = 'KONTINUERLIG_TILSYN_OG_PLEIE',
  TO_OMSORGSPERSONER = 'TO_OMSORGSPERSONER',
  LIVETS_SLUTTFASE = 'LIVETS_SLUTTFASE',
  LANGVARIG_SYKDOM = 'LANGVARIG_SYKDOM',
}

export default Vurderingstype;
