/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const dodEtikett: string;
declare const defaultBostedSoker: string;
declare const etikettMargin: string;
declare const paddingBottom: string;

export {
	dodEtikett,
	defaultBostedSoker,
	etikettMargin,
	paddingBottom
};

declare const __default_export__: {
	dodEtikett: typeof dodEtikett;
	defaultBostedSoker: typeof defaultBostedSoker;
	etikettMargin: typeof etikettMargin;
	paddingBottom: typeof paddingBottom;
};
export default __default_export__;
