/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const dodEtikett: string;
declare const defaultBostedSoker: string;
declare const etikettMargin: string;
declare const paddingBottom: string;

export {
	dodEtikett,
	defaultBostedSoker,
	etikettMargin,
	paddingBottom
};

declare const __default_export__: {
	dodEtikett: typeof dodEtikett;
	defaultBostedSoker: typeof defaultBostedSoker;
	etikettMargin: typeof etikettMargin;
	paddingBottom: typeof paddingBottom;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYm9zdGVkU29rZXJWaWV3Lm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsiYm9zdGVkU29rZXJWaWV3Lm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQUtBO2NBSUE7Y0FJQTs7O0NBYkE7Q0FLQTtDQUlBO0NBSUE7Ozs7Q0FiQTtDQUtBO0NBSUE7Q0FJQTs7In0=
