/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const pillIcon: string;
declare const pillIconSuccess: string;
declare const pillIconWarning: string;
declare const pillIconInfo: string;

export {
	pillIcon,
	pillIconSuccess,
	pillIconWarning,
	pillIconInfo
};

declare const __default_export__: {
	pillIcon: typeof pillIcon;
	pillIconSuccess: typeof pillIconSuccess;
	pillIconWarning: typeof pillIconWarning;
	pillIconInfo: typeof pillIconInfo;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiUGlsbEljb24ubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJQaWxsSWNvbi5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FDQTtjQUNBO2NBQ0E7OztDQUhBO0NBQ0E7Q0FDQTtDQUNBOzs7O0NBSEE7Q0FDQTtDQUNBO0NBQ0E7OyJ9
