/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const periodList: string;
declare const element: string;
declare const content: string;
declare const item: string;

export {
	periodList,
	element,
	content,
	item
};

declare const __default_export__: {
	periodList: typeof periodList;
	element: typeof element;
	content: typeof content;
	item: typeof item;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicGVyaW9kTGlzdC5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbInBlcmlvZExpc3QubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBTVk7Y0FTUztjQVlTOzs7Q0EzQjlCO0NBTVk7Q0FTUztDQVlTOzs7O0NBM0I5QjtDQU1ZO0NBU1M7Q0FZUzs7In0=
