export type {
  sif_tilbakekreving_behandling_modell_BehandlingFeilutbetalingFakta as BehandlingFeilutbetalingFakta,
  sif_tilbakekreving_web_app_tjenester_behandling_dto_BehandlingFeilutbetalingFaktaDto as BehandlingFeilutbetalingFaktaDto,
  sif_tilbakekreving_behandling_modell_LogiskPeriodeMedFaktaDto as LogiskPeriodeMedFaktaDto,
} from '@k9-sak-web/backend/ungtilbake/generated/types.js';
