enum VurderingÅrsak {
  INGEN_VURDERING = 'INGEN_VURDERING',
  OPPGITT_ANNEN_AKTIVITET = 'OPPGITT_ANNEN_AKTIVITET',
  OPPGITT_ARBEIDSFORHOLD = 'OPPGITT_ARBEIDSFORHOLD',
  OPPGITT_UTENLANDSK_ARBEIDSFORHOLD = 'OPPGITT_UTENLANDSK_ARBEIDSFORHOLD',
  OPPGITT_FRILANS = 'OPPGITT_FRILANS',
  YRKESAKTIVITET_0_PROSENT = 'YRKESAKTIVITET_0_PROSENT',
  YRKESAKTIVITET_MED_FRILANSOPPDRAG = 'YRKESAKTIVITET_MED_FRILANSOPPDRAG',
  ARBEIDSFORHOLD_LAGT_TIL_AV_SAKSBEHANDLER = 'ARBEIDSFORHOLD_LAGT_TIL_AV_SAKSBEHANDLER',
  MANUELT_OVERSTYRT = 'MANUELT_OVERSTYRT',
}
export default VurderingÅrsak;
