/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const basicList: string;
declare const element: string;

export {
	basicList,
	element
};

declare const __default_export__: {
	basicList: typeof basicList;
	element: typeof element;
};
export default __default_export__;
