/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const basicList: string;
declare const element: string;

export {
	basicList,
	element
};

declare const __default_export__: {
	basicList: typeof basicList;
	element: typeof element;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYmFzaWNMaXN0Lm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsiYmFzaWNMaXN0Lm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQU1BOzs7Q0FOQTtDQU1BOzs7O0NBTkE7Q0FNQTs7In0=
