/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const relatertFagsak: string;
declare const relatertFagsakNameGenderContainer: string;
declare const relatertFagsakIcon: string;
declare const relatertFagsakDescription: string;
declare const relatertFagsakSelector: string;
declare const relatertFagsakSelectorPushLeft: string;
declare const relatertFagsakName: string;
declare const relatertFagsakCenteredFlex: string;
declare const relatertFagsakS_kerSelect: string;
declare const relatertFagsakMarginLeft: string;
declare const relatertFagsakLock: string;

export {
	relatertFagsak,
	relatertFagsakNameGenderContainer,
	relatertFagsakIcon,
	relatertFagsakDescription,
	relatertFagsakSelector,
	relatertFagsakSelectorPushLeft,
	relatertFagsakName,
	relatertFagsakCenteredFlex,
	relatertFagsakMarginLeft,
	relatertFagsakLock
};

declare const __default_export__: {
	relatertFagsak: typeof relatertFagsak;
	relatertFagsakNameGenderContainer: typeof relatertFagsakNameGenderContainer;
	relatertFagsakIcon: typeof relatertFagsakIcon;
	relatertFagsakDescription: typeof relatertFagsakDescription;
	relatertFagsakSelector: typeof relatertFagsakSelector;
	relatertFagsakSelectorPushLeft: typeof relatertFagsakSelectorPushLeft;
	relatertFagsakName: typeof relatertFagsakName;
	relatertFagsakCenteredFlex: typeof relatertFagsakCenteredFlex;
	"relatertFagsakSøkerSelect": typeof relatertFagsakS_kerSelect;
	relatertFagsakMarginLeft: typeof relatertFagsakMarginLeft;
	relatertFagsakLock: typeof relatertFagsakLock;
};
export default __default_export__;
