/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const relatertFagsak: string;
declare const relatertFagsakNameGenderContainer: string;
declare const relatertFagsakIcon: string;
declare const relatertFagsakDescription: string;
declare const relatertFagsakSelector: string;
declare const relatertFagsakSelectorPushLeft: string;
declare const relatertFagsakName: string;
declare const relatertFagsakCenteredFlex: string;
declare const relatertFagsakS_kerSelect: string;
declare const relatertFagsakMarginLeft: string;
declare const relatertFagsakLock: string;

export {
	relatertFagsak,
	relatertFagsakNameGenderContainer,
	relatertFagsakIcon,
	relatertFagsakDescription,
	relatertFagsakSelector,
	relatertFagsakSelectorPushLeft,
	relatertFagsakName,
	relatertFagsakCenteredFlex,
	relatertFagsakMarginLeft,
	relatertFagsakLock
};

declare const __default_export__: {
	relatertFagsak: typeof relatertFagsak;
	relatertFagsakNameGenderContainer: typeof relatertFagsakNameGenderContainer;
	relatertFagsakIcon: typeof relatertFagsakIcon;
	relatertFagsakDescription: typeof relatertFagsakDescription;
	relatertFagsakSelector: typeof relatertFagsakSelector;
	relatertFagsakSelectorPushLeft: typeof relatertFagsakSelectorPushLeft;
	relatertFagsakName: typeof relatertFagsakName;
	relatertFagsakCenteredFlex: typeof relatertFagsakCenteredFlex;
	"relatertFagsakSøkerSelect": typeof relatertFagsakS_kerSelect;
	relatertFagsakMarginLeft: typeof relatertFagsakMarginLeft;
	relatertFagsakLock: typeof relatertFagsakLock;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicmVsYXRlcnRGYWdzYWsubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJyZWxhdGVydEZhZ3Nhay5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FVQTtjQU1BO2NBTUE7Y0FJQTtjQTZCQTtjQUlBO2NBT0E7Y0FNQTtjQWFBO2NBSUE7OztDQXpGQTtDQVVBO0NBTUE7Q0FNQTtDQUlBO0NBNkJBO0NBSUE7Q0FPQTtDQW1CQTtDQUlBOzs7O0NBekZBO0NBVUE7Q0FNQTtDQU1BO0NBSUE7Q0E2QkE7Q0FJQTtDQU9BOztDQW1CQTtDQUlBOzsifQ==
