/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const aksjonspunkt: string;
declare const erAksjonspunktApent: string;

export { aksjonspunkt, erAksjonspunktApent };

declare const __default_export__: {
  aksjonspunkt: typeof aksjonspunkt;
  erAksjonspunktApent: typeof erAksjonspunktApent;
};
export default __default_export__;
