/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const aksjonspunkt: string;
declare const erAksjonspunktApent: string;

export {
	aksjonspunkt,
	erAksjonspunktApent
};

declare const __default_export__: {
	aksjonspunkt: typeof aksjonspunkt;
	erAksjonspunktApent: typeof erAksjonspunktApent;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYWtzam9uc3B1bmt0Qm94Lm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsiYWtzam9uc3B1bmt0Qm94Lm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQUFhOzs7Q0FBYjtDQUFhOzs7O0NBQWI7Q0FBYTs7In0=
