/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const divider: string;
declare const image: string;
declare const modal: string;
declare const settPaVentModal: string;
declare const label: string;
declare const button: string;
declare const marginTop20: string;
declare const marginTop10: string;
declare const datePicker: string;
declare const flexContainer: string;
declare const selectContainer: string;
declare const calendarContainer: string;
declare const topContainer: string;
declare const contentContainer: string;
declare const buttonContainer: string;
declare const disabledNavSelect: string;
declare const commentInputLabel: string;

export {
	divider,
	image,
	modal,
	settPaVentModal,
	label,
	button,
	marginTop20,
	marginTop10,
	datePicker,
	flexContainer,
	selectContainer,
	calendarContainer,
	topContainer,
	contentContainer,
	buttonContainer,
	disabledNavSelect,
	commentInputLabel
};

declare const __default_export__: {
	divider: typeof divider;
	image: typeof image;
	modal: typeof modal;
	settPaVentModal: typeof settPaVentModal;
	label: typeof label;
	button: typeof button;
	marginTop20: typeof marginTop20;
	marginTop10: typeof marginTop10;
	datePicker: typeof datePicker;
	flexContainer: typeof flexContainer;
	selectContainer: typeof selectContainer;
	calendarContainer: typeof calendarContainer;
	topContainer: typeof topContainer;
	contentContainer: typeof contentContainer;
	buttonContainer: typeof buttonContainer;
	disabledNavSelect: typeof disabledNavSelect;
	commentInputLabel: typeof commentInputLabel;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2V0dFDDpVZlbnRNb2RhbC5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbInNldHRQw6VWZW50TW9kYWwubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFBO2NBU0E7Y0FLQTtjQUFNO2NBUU47Y0FJQTtjQUtBO2NBSUE7Y0FJQTtjQWlCQTtjQUlBO2NBSUE7Y0FLQTtjQUtBO2NBSUE7Y0FLQTtjQUlBOzs7Q0F2RkE7Q0FTQTtDQUtBO0NBQU07Q0FRTjtDQUlBO0NBS0E7Q0FJQTtDQUlBO0NBaUJBO0NBSUE7Q0FJQTtDQUtBO0NBS0E7Q0FJQTtDQUtBO0NBSUE7Ozs7Q0F2RkE7Q0FTQTtDQUtBO0NBQU07Q0FRTjtDQUlBO0NBS0E7Q0FJQTtDQUlBO0NBaUJBO0NBSUE7Q0FJQTtDQUtBO0NBS0E7Q0FJQTtDQUtBO0NBSUE7OyJ9
