/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const tabsList: string;
declare const tabPanel: string;
declare const tabellPanel: string;
declare const timelinePanelContent: string;
declare const controlsRow: string;
declare const controlsButtonGroup: string;
declare const controlsIconButton: string;
declare const kolonneYtelse: string;
declare const kolonnePeriode: string;
declare const kolonneStatus: string;
declare const kolonneSaksnr: string;
declare const tableWrapper: string;
declare const tabell: string;
declare const detaljerPopover: string;
declare const tidslinje: string;
declare const infoAlert: string;
declare const rowLabelBold: string;

export {
	tabsList,
	tabPanel,
	tabellPanel,
	timelinePanelContent,
	controlsRow,
	controlsButtonGroup,
	controlsIconButton,
	kolonneYtelse,
	kolonnePeriode,
	kolonneStatus,
	kolonneSaksnr,
	tableWrapper,
	tabell,
	detaljerPopover,
	tidslinje,
	infoAlert,
	rowLabelBold
};

declare const __default_export__: {
	tabsList: typeof tabsList;
	tabPanel: typeof tabPanel;
	tabellPanel: typeof tabellPanel;
	timelinePanelContent: typeof timelinePanelContent;
	controlsRow: typeof controlsRow;
	controlsButtonGroup: typeof controlsButtonGroup;
	controlsIconButton: typeof controlsIconButton;
	kolonneYtelse: typeof kolonneYtelse;
	kolonnePeriode: typeof kolonnePeriode;
	kolonneStatus: typeof kolonneStatus;
	kolonneSaksnr: typeof kolonneSaksnr;
	tableWrapper: typeof tableWrapper;
	tabell: typeof tabell;
	detaljerPopover: typeof detaljerPopover;
	tidslinje: typeof tidslinje;
	infoAlert: typeof infoAlert;
	rowLabelBold: typeof rowLabelBold;
};
export default __default_export__;
