/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const image: string;
declare const starIcon: string;
declare const noDocuments: string;
declare const borderTop: string;
declare const modiaLink: string;
declare const externalIcon: string;
declare const controlsContainer: string;
declare const documentAnchor: string;
declare const documentAnchorPlain: string;

export {
	image,
	starIcon,
	noDocuments,
	borderTop,
	modiaLink,
	externalIcon,
	controlsContainer,
	documentAnchor,
	documentAnchorPlain
};

declare const __default_export__: {
	image: typeof image;
	starIcon: typeof starIcon;
	noDocuments: typeof noDocuments;
	borderTop: typeof borderTop;
	modiaLink: typeof modiaLink;
	externalIcon: typeof externalIcon;
	controlsContainer: typeof controlsContainer;
	documentAnchor: typeof documentAnchor;
	documentAnchorPlain: typeof documentAnchorPlain;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZG9jdW1lbnRMaXN0Lm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsiZG9jdW1lbnRMaXN0Lm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQU1BO2NBUUE7Y0FJQTtjQUlBO2NBTUE7Y0FLQTtjQU9BO2NBUUE7OztDQWhEQTtDQU1BO0NBUUE7Q0FJQTtDQUlBO0NBTUE7Q0FLQTtDQU9BO0NBUUE7Ozs7Q0FoREE7Q0FNQTtDQVFBO0NBSUE7Q0FJQTtDQU1BO0NBS0E7Q0FPQTtDQVFBOzsifQ==
