/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const image: string;
declare const starIcon: string;
declare const noDocuments: string;
declare const borderTop: string;
declare const modiaLink: string;
declare const externalIcon: string;
declare const controlsContainer: string;
declare const documentAnchor: string;
declare const documentAnchorPlain: string;

export {
	image,
	starIcon,
	noDocuments,
	borderTop,
	modiaLink,
	externalIcon,
	controlsContainer,
	documentAnchor,
	documentAnchorPlain
};

declare const __default_export__: {
	image: typeof image;
	starIcon: typeof starIcon;
	noDocuments: typeof noDocuments;
	borderTop: typeof borderTop;
	modiaLink: typeof modiaLink;
	externalIcon: typeof externalIcon;
	controlsContainer: typeof controlsContainer;
	documentAnchor: typeof documentAnchor;
	documentAnchorPlain: typeof documentAnchorPlain;
};
export default __default_export__;
