/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const firstHeaderCell: string;
declare const firstDataCell: string;
declare const lastRow: string;
declare const exclamationmarkIcon: string;
declare const checkmarkIcon: string;

export {
	firstHeaderCell,
	firstDataCell,
	lastRow,
	exclamationmarkIcon,
	checkmarkIcon
};

declare const __default_export__: {
	firstHeaderCell: typeof firstHeaderCell;
	firstDataCell: typeof firstDataCell;
	lastRow: typeof lastRow;
	exclamationmarkIcon: typeof exclamationmarkIcon;
	checkmarkIcon: typeof checkmarkIcon;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYXJiZWlkT2dJbm50ZWt0Lm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsiYXJiZWlkT2dJbm50ZWt0Lm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQUlBO2NBSUE7Y0FJQTtjQUtBOzs7Q0FqQkE7Q0FJQTtDQUlBO0NBSUE7Q0FLQTs7OztDQWpCQTtDQUlBO0NBSUE7Q0FJQTtDQUtBOzsifQ==
