/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const sum: string;
declare const sumLabel: string;

export {
	sum,
	sumLabel
};

declare const __default_export__: {
	sum: typeof sum;
	sumLabel: typeof sumLabel;
};
export default __default_export__;
