/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const sum: string;
declare const sumLabel: string;

export {
	sum,
	sumLabel
};

declare const __default_export__: {
	sum: typeof sum;
	sumLabel: typeof sumLabel;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZGV0YWxqZXJPbUlubnRla3QubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJkZXRhbGplck9tSW5udGVrdC5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FVQTs7O0NBVkE7Q0FVQTs7OztDQVZBO0NBVUE7OyJ9
