/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const divider: string;
declare const image: string;
declare const modal: string;
declare const text: string;
declare const detail: string;
declare const cancelButton: string;

export {
	divider,
	image,
	modal,
	text,
	detail,
	cancelButton
};

declare const __default_export__: {
	divider: typeof divider;
	image: typeof image;
	modal: typeof modal;
	text: typeof text;
	detail: typeof detail;
	cancelButton: typeof cancelButton;
};
export default __default_export__;
