/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const link: string;
declare const lukkContainer: string;
declare const wordWrap: string;

export {
	container,
	link,
	lukkContainer,
	wordWrap
};

declare const __default_export__: {
	container: typeof container;
	link: typeof link;
	lukkContainer: typeof lukkContainer;
	wordWrap: typeof wordWrap;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZXJyb3JNZXNzYWdlUGFuZWwubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJlcnJvck1lc3NhZ2VQYW5lbC5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FhQTtjQWdCQTtjQU9BOzs7Q0FwQ0E7Q0FhQTtDQWdCQTtDQU9BOzs7O0NBcENBO0NBYUE7Q0FnQkE7Q0FPQTs7In0=
