/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const link: string;
declare const lukkContainer: string;
declare const wordWrap: string;

export { container, link, lukkContainer, wordWrap };

declare const __default_export__: {
  container: typeof container;
  link: typeof link;
  lukkContainer: typeof lukkContainer;
  wordWrap: typeof wordWrap;
};
export default __default_export__;
