/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const divider: string;
declare const image: string;
declare const modal: string;
declare const text: string;
declare const detail: string;
declare const cancelButton: string;

export {
	divider,
	image,
	modal,
	text,
	detail,
	cancelButton
};

declare const __default_export__: {
	divider: typeof divider;
	image: typeof image;
	modal: typeof modal;
	text: typeof text;
	detail: typeof detail;
	cancelButton: typeof cancelButton;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZXJyb3JNZXNzYWdlRGV0YWlsc01vZGFsLm1vZHVsZS5jc3MuZC50cyIsInNvdXJjZXMiOlsiZXJyb3JNZXNzYWdlRGV0YWlsc01vZGFsLm1vZHVsZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Y0FBQTtjQVNBO2NBTUE7Y0FLQTtjQUlBO2NBS007OztDQTdCTjtDQVNBO0NBTUE7Q0FLQTtDQUlBO0NBS007Ozs7Q0E3Qk47Q0FTQTtDQU1BO0NBS0E7Q0FJQTtDQUtNOzsifQ==
