/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const endringsloggContainer: string;
declare const containerDev: string;

export { endringsloggContainer, containerDev };

declare const __default_export__: {
  endringsloggContainer: typeof endringsloggContainer;
  containerDev: typeof containerDev;
};
export default __default_export__;
