/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const endringsloggContainer: string;
declare const containerDev: string;

export {
	endringsloggContainer,
	containerDev
};

declare const __default_export__: {
	endringsloggContainer: typeof endringsloggContainer;
	containerDev: typeof containerDev;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaGVhZGVyV2l0aEVycm9yUGFuZWwubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJoZWFkZXJXaXRoRXJyb3JQYW5lbC5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0EwQkE7OztDQTFCQTtDQTBCQTs7OztDQTFCQTtDQTBCQTs7In0=
