/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const divider: string;
declare const image: string;
declare const oneElement: string;
declare const severalElements: string;
declare const aksjonspunktText: string;
declare const wordwrap: string;

export { container, divider, image, oneElement, severalElements, aksjonspunktText, wordwrap };

declare const __default_export__: {
  container: typeof container;
  divider: typeof divider;
  image: typeof image;
  oneElement: typeof oneElement;
  severalElements: typeof severalElements;
  aksjonspunktText: typeof aksjonspunktText;
  wordwrap: typeof wordwrap;
};
export default __default_export__;
