/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const divider: string;
declare const image: string;
declare const oneElement: string;
declare const severalElements: string;
declare const aksjonspunktText: string;
declare const wordwrap: string;

export {
	container,
	divider,
	image,
	oneElement,
	severalElements,
	aksjonspunktText,
	wordwrap
};

declare const __default_export__: {
	container: typeof container;
	divider: typeof divider;
	image: typeof image;
	oneElement: typeof oneElement;
	severalElements: typeof severalElements;
	aksjonspunktText: typeof aksjonspunktText;
	wordwrap: typeof wordwrap;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYWtzam9uc3B1bmt0SGVscFRleHQubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJha3Nqb25zcHVua3RIZWxwVGV4dC5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FNQTtjQVNBO2NBS0E7Y0FNQTtjQUtBO2NBS0E7OztDQXBDQTtDQU1BO0NBU0E7Q0FLQTtDQU1BO0NBS0E7Q0FLQTs7OztDQXBDQTtDQU1BO0NBU0E7Q0FLQTtDQU1BO0NBS0E7Q0FLQTs7In0=
