import type { k9_sak_web_app_tjenester_behandling_opplæringspenger_visning_opplæring_OpplæringVurderingDto } from '@k9-sak-web/backend/k9sak/generated/types.js';

export type OpplæringVurderingDto = k9_sak_web_app_tjenester_behandling_opplæringspenger_visning_opplæring_OpplæringVurderingDto;
