const ReisetidStatus = {
  IKKE_VURDERT: 'MÅ_VURDERES',
  AUTOMATISK_GODKJENT: 'AUTOMATISK_GODKJENT',
  AUTOMATISK_AVSLAG: 'AUTOMATISK_AVSLAG',
  MANUELT_GODKJENT: 'MANUELT_GODKJENT',
  MANUELT_AVSLAG: 'MANUELT_AVSLAG',
};

export default ReisetidStatus;
