/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const previewLink: string;
declare const selectReadOnly: string;
declare const confirmVilkarForm: string;
declare const panel: string;
declare const fritekstTilBrevTextArea: string;
declare const explanationTextarea: string;

export {
	previewLink,
	selectReadOnly,
	confirmVilkarForm,
	panel,
	fritekstTilBrevTextArea,
	explanationTextarea
};

declare const __default_export__: {
	previewLink: typeof previewLink;
	selectReadOnly: typeof selectReadOnly;
	confirmVilkarForm: typeof confirmVilkarForm;
	panel: typeof panel;
	fritekstTilBrevTextArea: typeof fritekstTilBrevTextArea;
	explanationTextarea: typeof explanationTextarea;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoia2xhZ2VWdXJkZXJpbmdSYWRpb09wdGlvbnNOZnAubW9kdWxlLmNzcy5kLnRzIiwic291cmNlcyI6WyJrbGFnZVZ1cmRlcmluZ1JhZGlvT3B0aW9uc05mcC5tb2R1bGUuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7O2NBQUE7Y0FPQTtjQUlBO2NBSUE7Y0FJQTtjQUlBOzs7Q0F2QkE7Q0FPQTtDQUlBO0NBSUE7Q0FJQTtDQUlBOzs7O0NBdkJBO0NBT0E7Q0FJQTtDQUlBO0NBSUE7Q0FJQTs7In0=
