/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const previewLink: string;
declare const selectReadOnly: string;
declare const confirmVilkarForm: string;
declare const panel: string;
declare const fritekstTilBrevTextArea: string;
declare const explanationTextarea: string;

export { previewLink, selectReadOnly, confirmVilkarForm, panel, fritekstTilBrevTextArea, explanationTextarea };

declare const __default_export__: {
  previewLink: typeof previewLink;
  selectReadOnly: typeof selectReadOnly;
  confirmVilkarForm: typeof confirmVilkarForm;
  panel: typeof panel;
  fritekstTilBrevTextArea: typeof fritekstTilBrevTextArea;
  explanationTextarea: typeof explanationTextarea;
};
export default __default_export__;
