name: 'Install and cache Playwright'
description: Run commands needed to install and cache Playwright.
inputs:
  cacheOnly:
    description: Is this for caching purposes only?
    default: 'false'

runs:
  using: composite
  steps:
    - name: Finn Playwright versjon
      shell: bash
      run: |
        PLAYWRIGHT_VERSION=$(YARN_ENABLE_COLORS=false yarn info @playwright/test | grep @playwright | sed 's/.*://')
        echo "Playwright's Version: $PLAYWRIGHT_VERSION"
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

    - name: Cache Playwright Browsers for Playwright versjon
      id: cache-playwright-browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

    - name: Installer Playwright med avhengigheter
      shell: bash
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - name: Installer Playwrights avhengigheter
      shell: bash
      if: inputs.cacheOnly == 'false' && steps.cache-playwright-browsers.outputs.cache-hit == 'true'
      run: npx playwright install-deps
