name: 'Install and cache Playwright'
description: Run commands needed to install and cache Playwright.
inputs:
  cacheOnly:
    description: Is this for caching purposes only?
    default: 'false'

runs:
  using: composite
  steps:
    - name: Cache Playwright Browsers
      id: cache-playwright-browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ hashFiles('**/yarn.lock') }}

    - name: Installer Playwright med avhengigheter
      shell: bash
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - name: Installer Playwright med avhengigheter
      shell: bash
      if: inputs.cacheOnly == 'false' && steps.cache-playwright-browsers.outputs.cache-hit == 'true'
      run: npx playwright install-deps