name: 'Install and cache Playwright'
description: Run commands needed to install and cache Playwright.
inputs:
  cacheOnly:
    description: Is this for caching purposes only?
    default: 'false'

runs:
  using: composite
  steps:
    - name: Get Playwright version
      id: playwright-version
      shell: bash
      run: |
        PLAYWRIGHT_VERSION=$(node -p "require('./package.json').devDependencies['@playwright/test']")
        echo "version=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT

    - name: Cache Playwright Browsers
      id: cache-playwright-browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ steps.playwright-version.outputs.version }}

    - name: Installer Playwright med avhengigheter
      shell: bash
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps chromium

    - name: Installer Playwrights avhengigheter
      shell: bash
      if: inputs.cacheOnly == 'false'
      run: npx playwright install-deps chromium