enum SupportTabs {
  TIL_BESLUTTER = 'TIL_BESLUTTER',
  FRA_BESLUTTER = 'FRA_BESLUTTER',
  HISTORIKK = 'HISTORIKK',
  MELDINGER = 'MELDINGER',
  DOKUMENTER = 'DOKUMENTER',
}

export default SupportTabs;
