/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const button: string;
declare const divider: string;
declare const image: string;
declare const modal: string;

export {
	button,
	divider,
	image,
	modal
};

declare const __default_export__: {
	button: typeof button;
	divider: typeof divider;
	image: typeof image;
	modal: typeof modal;
};
export default __default_export__;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZmF0dGVyVmVkdGFrQXBwcm92YWxNb2RhbC5tb2R1bGUuY3NzLmQudHMiLCJzb3VyY2VzIjpbImZhdHRlclZlZHRha0FwcHJvdmFsTW9kYWwubW9kdWxlLmNzcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7OztjQUFNO2NBSU47Y0FXQTtjQU1BOzs7Q0FyQk07Q0FJTjtDQVdBO0NBTUE7Ozs7Q0FyQk07Q0FJTjtDQVdBO0NBTUE7OyJ9
