name: Copilot Setup Steps

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    name: Setup development environment for Copilot
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v5

      - name: Setup yarnrc.yml
        uses: ./.github/actions/setup-yarnrc
        with:
          npmAuthToken: ${{ secrets.READER_TOKEN }}

      - name: Sette opp node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: yarn

      - name: Installere dependencies
        run: HUSKY=0 yarn install --immutable
