name: Copilot Setup Steps

permissions:
  contents: read
  packages: read

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    name: Setup development environment for Copilot
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v5

      - name: Setup + Install
        uses: ./.github/actions/setup-install
        with:
          npmAuthToken: ${{ secrets.READER_TOKEN }}
