name: Build and Publish Storybook to GitHub Pages
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Hente kode
        uses: actions/checkout@v6

      - name: Sette opp pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Sette opp Node
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "pnpm"

      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.4
        with:
          install_command: LEFTHOOK=0 pnpm install --frozen-lockfile
          build_command: pnpm build-storybook
          path: .static_storybook
          checkout: false
