name: Build and Publish Storybook to GitHub Pages
on:
  push:
    branches:
      - feature/errorhandling
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: feature/errorhandling

      - name: Setup yarnrc
        uses: ./.github/actions/setup-yarnrc
        with:
          npmAuthToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Sette opp Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "22"
          cache: "yarn"

      - uses: bitovi/github-actions-storybook-to-github-pages@ddd9d35f670cceedd2bfc444be681001b0709730 # v1.0.4
        with:
          install_command: LEFTHOOK=0 yarn install --immutable
          build_command: yarn build-storybook
          path: .static_storybook
          checkout: false
