name: Build and deploy dev-next1
on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'CODEOWNERS'
    branches:
      - sykdom-og-opplæring

jobs:
  build-deploy:
    name: Build and deploy Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      CLUSTER: dev-fss
    steps:
      - name: Hente kode
        uses: actions/checkout@v4

      - name: Setup + Install
        uses: ./.github/actions/setup-install
        with:
          npmAuthToken: ${{ secrets.READER_TOKEN }}

      - name: Bygge dist
        run: yarn build

      - name: Build and push to docker registry
        uses: navikt/sif-gha-workflows/.github/actions/maven/build-push-docker-image@main
        id: docker-push
        with:
          additional-tag: 'dev-next1'
          without_navikt_prefix: true
          push-image: true
      - name: Deploy to nais
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ env.CLUSTER }}
          RESOURCE: deploy/${{ env.CLUSTER }}-k9saksbehandling.yml
          VARS: deploy/dev-next1.yaml
          VAR: image=${{ steps.docker-push.outputs.image }}
