name: Slash command dispatch
on:
  issue_comment:
    types: [created]
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - name: Slash command dispatch
        uses: peter-evans/slash-command-dispatch@v3.0.0
        with:
          token: ${{ secrets.GA_P_TOKEN }}
          commands: promote
          issue-type: issue
          allow-edits: true
