name: Lint, typescript-sjekk og bygg
permissions:
  contents: read
  packages: read
on:
  workflow_call:
    inputs:
      run-build:
        required: false
        type: boolean
        default: false

jobs:
  lint-tscheck-build:
    name: Lint, typescript-sjekk og bygg
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup + Install
        uses: ./.github/actions/setup-install
        with:
          npmAuthToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Css modules typegenerator
        run: yarn css:modules:typegen

      - name: Typescript-sjekk
        run: yarn ts-check

      - name: Eslint
        run: yarn lint

      - name: CSS-lint
        run: yarn css:lint

      - name: Sjekker at koden bygger
        if: ${{inputs.run-build}}
        run: yarn build
        timeout-minutes: 30
