name: Lint, typescript-sjekk og bygg
permissions:
  contents: read
  packages: read
on:
  workflow_call:
    inputs:
      run-build:
        required: false
        type: boolean
        default: false

jobs:
  lint-tscheck-build:
    name: Lint, typescript-sjekk og bygg
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v6

      - name: Setup + Install
        uses: ./.github/actions/setup-install
        with:
          npmAuthToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Typescript-sjekk
        run: pnpm ts-check

      - name: Eslint
        run: pnpm lint

      - name: Css modules typegenerator check
        run: pnpm css:modules:typegen:check

      - name: CSS-lint
        run: pnpm css:lint

      - name: Sjekker at koden bygger
        if: ${{inputs.run-build}}
        run: pnpm build
        timeout-minutes: 30
