name: Lint, typescript-sjekk og bygg

on:
  workflow_call:
    inputs:
      run-build:
        required: false
        type: boolean
        default: false

jobs:
  lint-tscheck-build:
    name: Lint, typescript-sjekk og bygg
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v3

      - name: Sette opp Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@navikt'
          cache: 'yarn'

      - name: Installere dependencies
        run: HUSKY=0 yarn install --prefer-offline  --no-progress --immutable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Typescript-sjekk
        run: yarn ts-check

      - name: Linting
        run: yarn less:lint

      - name: Sjekker at koden bygger
        if: ${{inputs.run-build}}
        run: yarn build-ci
