name: "Storybook Tests"
permissions:
  contents: read
  packages: read
on:
  workflow_call:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.1-noble
    steps:
      - name: Hente kode
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup + Install
        uses: ./.github/actions/setup-install
        with:
          npmAuthToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Start Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "yarn storybook --ci --no-open" \
            "npx wait-on http://127.0.0.1:9001/iframe.html && yarn test-storybook --url http://127.0.0.1:9001 --maxWorkers=4"
