name: Tester
permissions:
  contents: read
  packages: read

on:
  workflow_call:

jobs:
  enhetstester:
    name: Vitest (shard ${{ matrix.shard }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2]
    steps:
      - name: Hente kode
        uses: actions/checkout@v6

      - name: Setup + Install
        uses: ./.github/actions/setup-install
        with:
          npmAuthToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Kjør tester (shard ${{ matrix.shard }})
        env:
          CI: true
        run: yarn test --silent=true --shard=${{ matrix.shard }}/2

  test-success:
    name: Kjør enhetstester
    runs-on: ubuntu-latest
    needs: enhetstester
    if: always()
    steps:
      - name: Verify test success
        if: needs.enhetstester.result != 'success'
        run: exit 1
