name: Deploy Docker image
on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'CODEOWNERS'
    branches:
      - verdkjede-reusable-workflow
jobs:
  # test:
  #   uses: ./.github/workflows/test.yml
  #   secrets: inherit

  # lint-tscheck-build:
  #   uses: ./.github/workflows/lint-tscheck-build.yml
  #   secrets: inherit
  #   with:
  #     run-build: false

  deploy-docker-image:
    name: Deploy Docker image
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      id-token: write
    # needs: [test, lint-tscheck-build]
    outputs:
      tag: ${{ steps.docker-push.outputs.tag }}
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      - name: Hente kode
        uses: actions/checkout@v4

      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.navikt.npmAlwaysAuth true
          yarn config set npmScopes.navikt.npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Sette opp Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Set timestamp
        run: echo "TIMESTAMP=$(expr $(date +%Y%m%d%H%M%S))" >> $GITHUB_ENV

      - name: Installere dependencies
        run: HUSKY=0 yarn install --immutable

      - name: Bygge dist
        run: yarn build

      - name: Opprett release med Sentry
        run: yarn sentry-release
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          tag: 'latest'
          team: k9saksbehandling
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Sett image for nais deploy
        run: |
          echo "IMAGE=${{steps.docker-push.outputs.image}}" >> $GITHUB_OUTPUT
          echo "TAG=${{steps.docker-push.outputs.tag}}" >> $GITHUB_OUTPUT


  verdikjede-tester:
    name: Verdikjedetester
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      issues: write
      packages: read
    uses: navikt/sif-gha-workflows/.github/workflows/verdikjede-test.yml@main
    if: github.ref_name == 'master'
    needs: deploy-docker-image
    with:
      tag: ${{ needs.deploy-docker-image.outputs.tag }}
  trivy:
    needs: [deploy-docker-image]
    uses: navikt/sif-gha-workflows/.github/workflows/trivy.yml@main
    permissions:
      contents: write
      id-token: write
      security-events: write
      actions: read
    secrets: inherit
    with:
      image: ${{ needs.deploy-docker-image.outputs.image }}
      team: k9saksbehandling
