/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const fremhevingTag: string;

export {
	fremhevingTag
};

declare const __default_export__: {
	fremhevingTag: typeof fremhevingTag;
};
export default __default_export__;
